/**
 * This file was auto-generated by Fern from our API Definition.
 */

package io.tradewatch.client.resources.currencies;

import io.tradewatch.client.core.ClientOptions;
import io.tradewatch.client.core.RequestOptions;
import io.tradewatch.client.resources.currencies.requests.CurrenciesConvertRequest;
import io.tradewatch.client.resources.currencies.requests.CurrenciesGetInsightsRequest;
import io.tradewatch.client.resources.currencies.requests.CurrenciesGetQuoteRequest;
import io.tradewatch.client.resources.currencies.requests.CurrenciesGetQuotesRequest;
import io.tradewatch.client.resources.currencies.requests.CurrenciesGetSymbolsRequest;
import io.tradewatch.client.types.Conversion;
import io.tradewatch.client.types.CursorPageTCustomizedNewsOut;
import io.tradewatch.client.types.CursorPageTCustomizedSymbolsOutFull;
import io.tradewatch.client.types.LastQuote;
import io.tradewatch.client.types.LastQuotes;
import java.lang.String;
import java.util.concurrent.CompletableFuture;

public class AsyncCurrenciesClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawCurrenciesClient rawClient;

  public AsyncCurrenciesClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawCurrenciesClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawCurrenciesClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Convert one symbol to another
   */
  public CompletableFuture<Conversion> convert(String from, String to) {
    return this.rawClient.convert(from, to).thenApply(response -> response.body());
  }

  /**
   * Convert one symbol to another
   */
  public CompletableFuture<Conversion> convert(String from, String to,
      RequestOptions requestOptions) {
    return this.rawClient.convert(from, to, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Convert one symbol to another
   */
  public CompletableFuture<Conversion> convert(String from, String to,
      CurrenciesConvertRequest request) {
    return this.rawClient.convert(from, to, request).thenApply(response -> response.body());
  }

  /**
   * Convert one symbol to another
   */
  public CompletableFuture<Conversion> convert(String from, String to,
      CurrenciesConvertRequest request, RequestOptions requestOptions) {
    return this.rawClient.convert(from, to, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get the last quote tick for the provided symbols.
   */
  public CompletableFuture<LastQuotes> getQuotes(CurrenciesGetQuotesRequest request) {
    return this.rawClient.getQuotes(request).thenApply(response -> response.body());
  }

  /**
   * Get the last quote tick for the provided symbols.
   */
  public CompletableFuture<LastQuotes> getQuotes(CurrenciesGetQuotesRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.getQuotes(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get the last quote tick for the provided symbol.
   */
  public CompletableFuture<LastQuote> getQuote(CurrenciesGetQuoteRequest request) {
    return this.rawClient.getQuote(request).thenApply(response -> response.body());
  }

  /**
   * Get the last quote tick for the provided symbol.
   */
  public CompletableFuture<LastQuote> getQuote(CurrenciesGetQuoteRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.getQuote(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get list of available symbols
   */
  public CompletableFuture<CursorPageTCustomizedSymbolsOutFull> getSymbols() {
    return this.rawClient.getSymbols().thenApply(response -> response.body());
  }

  /**
   * Get list of available symbols
   */
  public CompletableFuture<CursorPageTCustomizedSymbolsOutFull> getSymbols(
      RequestOptions requestOptions) {
    return this.rawClient.getSymbols(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get list of available symbols
   */
  public CompletableFuture<CursorPageTCustomizedSymbolsOutFull> getSymbols(
      CurrenciesGetSymbolsRequest request) {
    return this.rawClient.getSymbols(request).thenApply(response -> response.body());
  }

  /**
   * Get list of available symbols
   */
  public CompletableFuture<CursorPageTCustomizedSymbolsOutFull> getSymbols(
      CurrenciesGetSymbolsRequest request, RequestOptions requestOptions) {
    return this.rawClient.getSymbols(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get recent currencies insights.
   */
  public CompletableFuture<CursorPageTCustomizedNewsOut> getInsights() {
    return this.rawClient.getInsights().thenApply(response -> response.body());
  }

  /**
   * Get recent currencies insights.
   */
  public CompletableFuture<CursorPageTCustomizedNewsOut> getInsights(
      RequestOptions requestOptions) {
    return this.rawClient.getInsights(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get recent currencies insights.
   */
  public CompletableFuture<CursorPageTCustomizedNewsOut> getInsights(
      CurrenciesGetInsightsRequest request) {
    return this.rawClient.getInsights(request).thenApply(response -> response.body());
  }

  /**
   * Get recent currencies insights.
   */
  public CompletableFuture<CursorPageTCustomizedNewsOut> getInsights(
      CurrenciesGetInsightsRequest request, RequestOptions requestOptions) {
    return this.rawClient.getInsights(request, requestOptions).thenApply(response -> response.body());
  }
}
