/**
 * This file was auto-generated by Fern from our API Definition.
 */

package io.tradewatch.client.resources.stocks;

import io.tradewatch.client.core.ClientOptions;
import io.tradewatch.client.core.RequestOptions;
import io.tradewatch.client.resources.stocks.requests.StocksGetHistoricalOhlcRequest;
import io.tradewatch.client.resources.stocks.requests.StocksGetHistoricalTicksRequest;
import io.tradewatch.client.resources.stocks.requests.StocksGetInsightsRequest;
import io.tradewatch.client.resources.stocks.requests.StocksGetMarketHolidaysRequest;
import io.tradewatch.client.resources.stocks.requests.StocksGetMarketStatusRequest;
import io.tradewatch.client.resources.stocks.requests.StocksGetMarketsRequest;
import io.tradewatch.client.resources.stocks.requests.StocksGetQuoteRequest;
import io.tradewatch.client.resources.stocks.requests.StocksGetQuotesRequest;
import io.tradewatch.client.resources.stocks.requests.StocksGetStockDataRequest;
import io.tradewatch.client.resources.stocks.requests.StocksGetSymbolsRequest;
import io.tradewatch.client.resources.stocks.requests.StocksGetTradingHoursRequest;
import io.tradewatch.client.types.CountriesList;
import io.tradewatch.client.types.CursorPageTCustomizedHistoricalRawTick;
import io.tradewatch.client.types.CursorPageTCustomizedNewsOut;
import io.tradewatch.client.types.CursorPageTCustomizedSymbolsOutFullStocks;
import io.tradewatch.client.types.HistoricalOhlcResponse;
import io.tradewatch.client.types.LastQuote;
import io.tradewatch.client.types.LastQuotes;
import io.tradewatch.client.types.MarketHolidayResponse;
import io.tradewatch.client.types.MarketResponse;
import io.tradewatch.client.types.MarketStatusResponse;
import io.tradewatch.client.types.StockDataFlatResponse;
import io.tradewatch.client.types.TradingHoursResponse;
import java.lang.String;
import java.util.List;
import java.util.concurrent.CompletableFuture;

public class AsyncStocksClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawStocksClient rawClient;

  public AsyncStocksClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawStocksClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawStocksClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Get the last quote tick for the provided symbols.
   */
  public CompletableFuture<LastQuotes> getQuotes(StocksGetQuotesRequest request) {
    return this.rawClient.getQuotes(request).thenApply(response -> response.body());
  }

  /**
   * Get the last quote tick for the provided symbols.
   */
  public CompletableFuture<LastQuotes> getQuotes(StocksGetQuotesRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.getQuotes(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get the last quote tick for the provided symbol.
   */
  public CompletableFuture<LastQuote> getQuote(StocksGetQuoteRequest request) {
    return this.rawClient.getQuote(request).thenApply(response -> response.body());
  }

  /**
   * Get the last quote tick for the provided symbol.
   */
  public CompletableFuture<LastQuote> getQuote(StocksGetQuoteRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.getQuote(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get list of available symbols
   */
  public CompletableFuture<CursorPageTCustomizedSymbolsOutFullStocks> getSymbols() {
    return this.rawClient.getSymbols().thenApply(response -> response.body());
  }

  /**
   * Get list of available symbols
   */
  public CompletableFuture<CursorPageTCustomizedSymbolsOutFullStocks> getSymbols(
      RequestOptions requestOptions) {
    return this.rawClient.getSymbols(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get list of available symbols
   */
  public CompletableFuture<CursorPageTCustomizedSymbolsOutFullStocks> getSymbols(
      StocksGetSymbolsRequest request) {
    return this.rawClient.getSymbols(request).thenApply(response -> response.body());
  }

  /**
   * Get list of available symbols
   */
  public CompletableFuture<CursorPageTCustomizedSymbolsOutFullStocks> getSymbols(
      StocksGetSymbolsRequest request, RequestOptions requestOptions) {
    return this.rawClient.getSymbols(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get recent stocks insights.
   */
  public CompletableFuture<CursorPageTCustomizedNewsOut> getInsights() {
    return this.rawClient.getInsights().thenApply(response -> response.body());
  }

  /**
   * Get recent stocks insights.
   */
  public CompletableFuture<CursorPageTCustomizedNewsOut> getInsights(
      RequestOptions requestOptions) {
    return this.rawClient.getInsights(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get recent stocks insights.
   */
  public CompletableFuture<CursorPageTCustomizedNewsOut> getInsights(
      StocksGetInsightsRequest request) {
    return this.rawClient.getInsights(request).thenApply(response -> response.body());
  }

  /**
   * Get recent stocks insights.
   */
  public CompletableFuture<CursorPageTCustomizedNewsOut> getInsights(
      StocksGetInsightsRequest request, RequestOptions requestOptions) {
    return this.rawClient.getInsights(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get list of available countries
   */
  public CompletableFuture<CountriesList> stockGetCountries() {
    return this.rawClient.stockGetCountries().thenApply(response -> response.body());
  }

  /**
   * Get list of available countries
   */
  public CompletableFuture<CountriesList> stockGetCountries(RequestOptions requestOptions) {
    return this.rawClient.stockGetCountries(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get details about the markets available in this API.
   */
  public CompletableFuture<List<MarketResponse>> getMarkets() {
    return this.rawClient.getMarkets().thenApply(response -> response.body());
  }

  /**
   * Get details about the markets available in this API.
   */
  public CompletableFuture<List<MarketResponse>> getMarkets(RequestOptions requestOptions) {
    return this.rawClient.getMarkets(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get details about the markets available in this API.
   */
  public CompletableFuture<List<MarketResponse>> getMarkets(StocksGetMarketsRequest request) {
    return this.rawClient.getMarkets(request).thenApply(response -> response.body());
  }

  /**
   * Get details about the markets available in this API.
   */
  public CompletableFuture<List<MarketResponse>> getMarkets(StocksGetMarketsRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.getMarkets(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get the current status (open or closed) of a market. It takes holidays and half-days into account but does not factor in circuit breakers or halts.
   */
  public CompletableFuture<List<MarketStatusResponse>> getMarketStatus() {
    return this.rawClient.getMarketStatus().thenApply(response -> response.body());
  }

  /**
   * Get the current status (open or closed) of a market. It takes holidays and half-days into account but does not factor in circuit breakers or halts.
   */
  public CompletableFuture<List<MarketStatusResponse>> getMarketStatus(
      RequestOptions requestOptions) {
    return this.rawClient.getMarketStatus(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get the current status (open or closed) of a market. It takes holidays and half-days into account but does not factor in circuit breakers or halts.
   */
  public CompletableFuture<List<MarketStatusResponse>> getMarketStatus(
      StocksGetMarketStatusRequest request) {
    return this.rawClient.getMarketStatus(request).thenApply(response -> response.body());
  }

  /**
   * Get the current status (open or closed) of a market. It takes holidays and half-days into account but does not factor in circuit breakers or halts.
   */
  public CompletableFuture<List<MarketStatusResponse>> getMarketStatus(
      StocksGetMarketStatusRequest request, RequestOptions requestOptions) {
    return this.rawClient.getMarketStatus(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get trading hours. It takes half-days into account.
   */
  public CompletableFuture<List<TradingHoursResponse>> getTradingHours(
      StocksGetTradingHoursRequest request) {
    return this.rawClient.getTradingHours(request).thenApply(response -> response.body());
  }

  /**
   * Get trading hours. It takes half-days into account.
   */
  public CompletableFuture<List<TradingHoursResponse>> getTradingHours(
      StocksGetTradingHoursRequest request, RequestOptions requestOptions) {
    return this.rawClient.getTradingHours(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get market holidays. It takes half-days into account.
   */
  public CompletableFuture<List<MarketHolidayResponse>> getMarketHolidays(
      StocksGetMarketHolidaysRequest request) {
    return this.rawClient.getMarketHolidays(request).thenApply(response -> response.body());
  }

  /**
   * Get market holidays. It takes half-days into account.
   */
  public CompletableFuture<List<MarketHolidayResponse>> getMarketHolidays(
      StocksGetMarketHolidaysRequest request, RequestOptions requestOptions) {
    return this.rawClient.getMarketHolidays(request, requestOptions).thenApply(response -> response.body());
  }

  public CompletableFuture<StockDataFlatResponse> getStockData(String symbol) {
    return this.rawClient.getStockData(symbol).thenApply(response -> response.body());
  }

  public CompletableFuture<StockDataFlatResponse> getStockData(String symbol,
      RequestOptions requestOptions) {
    return this.rawClient.getStockData(symbol, requestOptions).thenApply(response -> response.body());
  }

  public CompletableFuture<StockDataFlatResponse> getStockData(String symbol,
      StocksGetStockDataRequest request) {
    return this.rawClient.getStockData(symbol, request).thenApply(response -> response.body());
  }

  public CompletableFuture<StockDataFlatResponse> getStockData(String symbol,
      StocksGetStockDataRequest request, RequestOptions requestOptions) {
    return this.rawClient.getStockData(symbol, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get historical OHLC candles for a symbol in a selected resolution and time range.
   */
  public CompletableFuture<HistoricalOhlcResponse> getHistoricalOhlc(String symbol,
      StocksGetHistoricalOhlcRequest request) {
    return this.rawClient.getHistoricalOhlc(symbol, request).thenApply(response -> response.body());
  }

  /**
   * Get historical OHLC candles for a symbol in a selected resolution and time range.
   */
  public CompletableFuture<HistoricalOhlcResponse> getHistoricalOhlc(String symbol,
      StocksGetHistoricalOhlcRequest request, RequestOptions requestOptions) {
    return this.rawClient.getHistoricalOhlc(symbol, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get raw historical ticks for a symbol in a selected time range using cursor pagination.
   */
  public CompletableFuture<CursorPageTCustomizedHistoricalRawTick> getHistoricalTicks(String symbol,
      StocksGetHistoricalTicksRequest request) {
    return this.rawClient.getHistoricalTicks(symbol, request).thenApply(response -> response.body());
  }

  /**
   * Get raw historical ticks for a symbol in a selected time range using cursor pagination.
   */
  public CompletableFuture<CursorPageTCustomizedHistoricalRawTick> getHistoricalTicks(String symbol,
      StocksGetHistoricalTicksRequest request, RequestOptions requestOptions) {
    return this.rawClient.getHistoricalTicks(symbol, request, requestOptions).thenApply(response -> response.body());
  }
}
