/**
 * This file was auto-generated by Fern from our API Definition.
 */

package io.tradewatch.client.resources.stocks;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import io.tradewatch.client.core.ClientOptions;
import io.tradewatch.client.core.ObjectMappers;
import io.tradewatch.client.core.QueryStringMapper;
import io.tradewatch.client.core.RequestOptions;
import io.tradewatch.client.core.TradewatchApiApiException;
import io.tradewatch.client.core.TradewatchApiException;
import io.tradewatch.client.core.TradewatchApiHttpResponse;
import io.tradewatch.client.errors.UnprocessableEntityError;
import io.tradewatch.client.resources.stocks.requests.StocksGetHistoricalOhlcRequest;
import io.tradewatch.client.resources.stocks.requests.StocksGetHistoricalTicksRequest;
import io.tradewatch.client.resources.stocks.requests.StocksGetInsightsRequest;
import io.tradewatch.client.resources.stocks.requests.StocksGetMarketHolidaysRequest;
import io.tradewatch.client.resources.stocks.requests.StocksGetMarketStatusRequest;
import io.tradewatch.client.resources.stocks.requests.StocksGetMarketsRequest;
import io.tradewatch.client.resources.stocks.requests.StocksGetQuoteRequest;
import io.tradewatch.client.resources.stocks.requests.StocksGetQuotesRequest;
import io.tradewatch.client.resources.stocks.requests.StocksGetStockDataRequest;
import io.tradewatch.client.resources.stocks.requests.StocksGetSymbolsRequest;
import io.tradewatch.client.resources.stocks.requests.StocksGetTradingHoursRequest;
import io.tradewatch.client.types.CountriesList;
import io.tradewatch.client.types.CursorPageTCustomizedHistoricalRawTick;
import io.tradewatch.client.types.CursorPageTCustomizedNewsOut;
import io.tradewatch.client.types.CursorPageTCustomizedSymbolsOutFullStocks;
import io.tradewatch.client.types.HistoricalOhlcResponse;
import io.tradewatch.client.types.LastQuote;
import io.tradewatch.client.types.LastQuotes;
import io.tradewatch.client.types.MarketHolidayResponse;
import io.tradewatch.client.types.MarketResponse;
import io.tradewatch.client.types.MarketStatusResponse;
import io.tradewatch.client.types.StockDataFlatResponse;
import io.tradewatch.client.types.TradingHoursResponse;
import java.io.IOException;
import java.lang.Object;
import java.lang.String;
import java.util.List;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawStocksClient {
  protected final ClientOptions clientOptions;

  public RawStocksClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Get the last quote tick for the provided symbols.
   */
  public TradewatchApiHttpResponse<LastQuotes> getQuotes(StocksGetQuotesRequest request) {
    return getQuotes(request,null);
  }

  /**
   * Get the last quote tick for the provided symbols.
   */
  public TradewatchApiHttpResponse<LastQuotes> getQuotes(StocksGetQuotesRequest request,
      RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("stocks/quotes");QueryStringMapper.addQueryParameter(httpUrl, "symbols", request.getSymbols(), false);
      if (request.getPrecision().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "precision", request.getPrecision().get(), false);
      }
      if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        if (response.isSuccessful()) {
          return new TradewatchApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, LastQuotes.class), response);
        }
        try {
          if (response.code() == 422) {
            throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
          }
        }
        catch (JsonProcessingException ignored) {
          // unable to map error response, throwing generic error
        }
        Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
        throw new TradewatchApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
      }
      catch (IOException e) {
        throw new TradewatchApiException("Network error executing HTTP request", e);
      }
    }

    /**
     * Get the last quote tick for the provided symbol.
     */
    public TradewatchApiHttpResponse<LastQuote> getQuote(StocksGetQuoteRequest request) {
      return getQuote(request,null);
    }

    /**
     * Get the last quote tick for the provided symbol.
     */
    public TradewatchApiHttpResponse<LastQuote> getQuote(StocksGetQuoteRequest request,
        RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("stocks/quote");QueryStringMapper.addQueryParameter(httpUrl, "symbol", request.getSymbol(), false);
        if (request.getPrecision().isPresent()) {
          QueryStringMapper.addQueryParameter(httpUrl, "precision", request.getPrecision().get(), false);
        }
        if (requestOptions != null) {
          requestOptions.getQueryParameters().forEach((_key, _value) -> {
            httpUrl.addQueryParameter(_key, _value);
          } );
        }
        Request.Builder _requestBuilder = new Request.Builder()
          .url(httpUrl.build())
          .method("GET", null)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
          ResponseBody responseBody = response.body();
          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
          if (response.isSuccessful()) {
            return new TradewatchApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, LastQuote.class), response);
          }
          try {
            if (response.code() == 422) {
              throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
            }
          }
          catch (JsonProcessingException ignored) {
            // unable to map error response, throwing generic error
          }
          Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
          throw new TradewatchApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
        }
        catch (IOException e) {
          throw new TradewatchApiException("Network error executing HTTP request", e);
        }
      }

      /**
       * Get list of available symbols
       */
      public TradewatchApiHttpResponse<CursorPageTCustomizedSymbolsOutFullStocks> getSymbols() {
        return getSymbols(StocksGetSymbolsRequest.builder().build());
      }

      /**
       * Get list of available symbols
       */
      public TradewatchApiHttpResponse<CursorPageTCustomizedSymbolsOutFullStocks> getSymbols(
          RequestOptions requestOptions) {
        return getSymbols(StocksGetSymbolsRequest.builder().build(),requestOptions);
      }

      /**
       * Get list of available symbols
       */
      public TradewatchApiHttpResponse<CursorPageTCustomizedSymbolsOutFullStocks> getSymbols(
          StocksGetSymbolsRequest request) {
        return getSymbols(request,null);
      }

      /**
       * Get list of available symbols
       */
      public TradewatchApiHttpResponse<CursorPageTCustomizedSymbolsOutFullStocks> getSymbols(
          StocksGetSymbolsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("stocks/symbols");if (request.getSize().isPresent()) {
            QueryStringMapper.addQueryParameter(httpUrl, "size", request.getSize().get(), false);
          }
          if (request.getMode().isPresent()) {
            QueryStringMapper.addQueryParameter(httpUrl, "mode", request.getMode().get(), false);
          }
          if (request.getType().isPresent()) {
            QueryStringMapper.addQueryParameter(httpUrl, "type", request.getType().get(), false);
          }
          if (request.getCountry().isPresent()) {
            QueryStringMapper.addQueryParameter(httpUrl, "country", request.getCountry().get(), false);
          }
          if (request.getCursor().isPresent()) {
            QueryStringMapper.addQueryParameter(httpUrl, "cursor", request.getCursor().get(), false);
          }
          if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
              httpUrl.addQueryParameter(_key, _value);
            } );
          }
          Request.Builder _requestBuilder = new Request.Builder()
            .url(httpUrl.build())
            .method("GET", null)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Accept", "application/json");
          Request okhttpRequest = _requestBuilder.build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
              return new TradewatchApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, CursorPageTCustomizedSymbolsOutFullStocks.class), response);
            }
            try {
              if (response.code() == 422) {
                throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new TradewatchApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
          }
          catch (IOException e) {
            throw new TradewatchApiException("Network error executing HTTP request", e);
          }
        }

        /**
         * Get recent stocks insights.
         */
        public TradewatchApiHttpResponse<CursorPageTCustomizedNewsOut> getInsights() {
          return getInsights(StocksGetInsightsRequest.builder().build());
        }

        /**
         * Get recent stocks insights.
         */
        public TradewatchApiHttpResponse<CursorPageTCustomizedNewsOut> getInsights(
            RequestOptions requestOptions) {
          return getInsights(StocksGetInsightsRequest.builder().build(),requestOptions);
        }

        /**
         * Get recent stocks insights.
         */
        public TradewatchApiHttpResponse<CursorPageTCustomizedNewsOut> getInsights(
            StocksGetInsightsRequest request) {
          return getInsights(request,null);
        }

        /**
         * Get recent stocks insights.
         */
        public TradewatchApiHttpResponse<CursorPageTCustomizedNewsOut> getInsights(
            StocksGetInsightsRequest request, RequestOptions requestOptions) {
          HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

            .addPathSegments("stocks/insights");if (request.getCursor().isPresent()) {
              QueryStringMapper.addQueryParameter(httpUrl, "cursor", request.getCursor().get(), false);
            }
            if (request.getSize().isPresent()) {
              QueryStringMapper.addQueryParameter(httpUrl, "size", request.getSize().get(), false);
            }
            if (requestOptions != null) {
              requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
              } );
            }
            Request.Builder _requestBuilder = new Request.Builder()
              .url(httpUrl.build())
              .method("GET", null)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Accept", "application/json");
            Request okhttpRequest = _requestBuilder.build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            try (Response response = client.newCall(okhttpRequest).execute()) {
              ResponseBody responseBody = response.body();
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              if (response.isSuccessful()) {
                return new TradewatchApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, CursorPageTCustomizedNewsOut.class), response);
              }
              try {
                if (response.code() == 422) {
                  throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
              }
              catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
              }
              Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
              throw new TradewatchApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
            }
            catch (IOException e) {
              throw new TradewatchApiException("Network error executing HTTP request", e);
            }
          }

          /**
           * Get list of available countries
           */
          public TradewatchApiHttpResponse<CountriesList> stockGetCountries() {
            return stockGetCountries(null);
          }

          /**
           * Get list of available countries
           */
          public TradewatchApiHttpResponse<CountriesList> stockGetCountries(
              RequestOptions requestOptions) {
            HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

              .addPathSegments("stocks/countries");if (requestOptions != null) {
                requestOptions.getQueryParameters().forEach((_key, _value) -> {
                  httpUrl.addQueryParameter(_key, _value);
                } );
              }
              Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
              OkHttpClient client = clientOptions.httpClient();
              if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                client = clientOptions.httpClientWithTimeout(requestOptions);
              }
              try (Response response = client.newCall(okhttpRequest).execute()) {
                ResponseBody responseBody = response.body();
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                if (response.isSuccessful()) {
                  return new TradewatchApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, CountriesList.class), response);
                }
                Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                throw new TradewatchApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
              }
              catch (IOException e) {
                throw new TradewatchApiException("Network error executing HTTP request", e);
              }
            }

            /**
             * Get details about the markets available in this API.
             */
            public TradewatchApiHttpResponse<List<MarketResponse>> getMarkets() {
              return getMarkets(StocksGetMarketsRequest.builder().build());
            }

            /**
             * Get details about the markets available in this API.
             */
            public TradewatchApiHttpResponse<List<MarketResponse>> getMarkets(
                RequestOptions requestOptions) {
              return getMarkets(StocksGetMarketsRequest.builder().build(),requestOptions);
            }

            /**
             * Get details about the markets available in this API.
             */
            public TradewatchApiHttpResponse<List<MarketResponse>> getMarkets(
                StocksGetMarketsRequest request) {
              return getMarkets(request,null);
            }

            /**
             * Get details about the markets available in this API.
             */
            public TradewatchApiHttpResponse<List<MarketResponse>> getMarkets(
                StocksGetMarketsRequest request, RequestOptions requestOptions) {
              HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

                .addPathSegments("stocks/markets");if (request.getMic().isPresent()) {
                  QueryStringMapper.addQueryParameter(httpUrl, "mic", request.getMic().get(), false);
                }
                if (requestOptions != null) {
                  requestOptions.getQueryParameters().forEach((_key, _value) -> {
                    httpUrl.addQueryParameter(_key, _value);
                  } );
                }
                Request.Builder _requestBuilder = new Request.Builder()
                  .url(httpUrl.build())
                  .method("GET", null)
                  .headers(Headers.of(clientOptions.headers(requestOptions)))
                  .addHeader("Accept", "application/json");
                Request okhttpRequest = _requestBuilder.build();
                OkHttpClient client = clientOptions.httpClient();
                if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                  client = clientOptions.httpClientWithTimeout(requestOptions);
                }
                try (Response response = client.newCall(okhttpRequest).execute()) {
                  ResponseBody responseBody = response.body();
                  String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                  if (response.isSuccessful()) {
                    return new TradewatchApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, new TypeReference<List<MarketResponse>>() {}), response);
                  }
                  try {
                    if (response.code() == 422) {
                      throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    }
                  }
                  catch (JsonProcessingException ignored) {
                    // unable to map error response, throwing generic error
                  }
                  Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                  throw new TradewatchApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
                }
                catch (IOException e) {
                  throw new TradewatchApiException("Network error executing HTTP request", e);
                }
              }

              /**
               * Get the current status (open or closed) of a market. It takes holidays and half-days into account but does not factor in circuit breakers or halts.
               */
              public TradewatchApiHttpResponse<List<MarketStatusResponse>> getMarketStatus() {
                return getMarketStatus(StocksGetMarketStatusRequest.builder().build());
              }

              /**
               * Get the current status (open or closed) of a market. It takes holidays and half-days into account but does not factor in circuit breakers or halts.
               */
              public TradewatchApiHttpResponse<List<MarketStatusResponse>> getMarketStatus(
                  RequestOptions requestOptions) {
                return getMarketStatus(StocksGetMarketStatusRequest.builder().build(),requestOptions);
              }

              /**
               * Get the current status (open or closed) of a market. It takes holidays and half-days into account but does not factor in circuit breakers or halts.
               */
              public TradewatchApiHttpResponse<List<MarketStatusResponse>> getMarketStatus(
                  StocksGetMarketStatusRequest request) {
                return getMarketStatus(request,null);
              }

              /**
               * Get the current status (open or closed) of a market. It takes holidays and half-days into account but does not factor in circuit breakers or halts.
               */
              public TradewatchApiHttpResponse<List<MarketStatusResponse>> getMarketStatus(
                  StocksGetMarketStatusRequest request, RequestOptions requestOptions) {
                HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

                  .addPathSegments("stocks/markets/status");if (request.getMic().isPresent()) {
                    QueryStringMapper.addQueryParameter(httpUrl, "mic", request.getMic().get(), false);
                  }
                  if (requestOptions != null) {
                    requestOptions.getQueryParameters().forEach((_key, _value) -> {
                      httpUrl.addQueryParameter(_key, _value);
                    } );
                  }
                  Request.Builder _requestBuilder = new Request.Builder()
                    .url(httpUrl.build())
                    .method("GET", null)
                    .headers(Headers.of(clientOptions.headers(requestOptions)))
                    .addHeader("Accept", "application/json");
                  Request okhttpRequest = _requestBuilder.build();
                  OkHttpClient client = clientOptions.httpClient();
                  if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                    client = clientOptions.httpClientWithTimeout(requestOptions);
                  }
                  try (Response response = client.newCall(okhttpRequest).execute()) {
                    ResponseBody responseBody = response.body();
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                      return new TradewatchApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, new TypeReference<List<MarketStatusResponse>>() {}), response);
                    }
                    try {
                      if (response.code() == 422) {
                        throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                      }
                    }
                    catch (JsonProcessingException ignored) {
                      // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    throw new TradewatchApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
                  }
                  catch (IOException e) {
                    throw new TradewatchApiException("Network error executing HTTP request", e);
                  }
                }

                /**
                 * Get trading hours. It takes half-days into account.
                 */
                public TradewatchApiHttpResponse<List<TradingHoursResponse>> getTradingHours(
                    StocksGetTradingHoursRequest request) {
                  return getTradingHours(request,null);
                }

                /**
                 * Get trading hours. It takes half-days into account.
                 */
                public TradewatchApiHttpResponse<List<TradingHoursResponse>> getTradingHours(
                    StocksGetTradingHoursRequest request, RequestOptions requestOptions) {
                  HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

                    .addPathSegments("stocks/markets/hours");if (request.getMic().isPresent()) {
                      QueryStringMapper.addQueryParameter(httpUrl, "mic", request.getMic().get(), false);
                    }
                    QueryStringMapper.addQueryParameter(httpUrl, "start", request.getStart(), false);
                    QueryStringMapper.addQueryParameter(httpUrl, "end", request.getEnd(), false);
                    if (requestOptions != null) {
                      requestOptions.getQueryParameters().forEach((_key, _value) -> {
                        httpUrl.addQueryParameter(_key, _value);
                      } );
                    }
                    Request.Builder _requestBuilder = new Request.Builder()
                      .url(httpUrl.build())
                      .method("GET", null)
                      .headers(Headers.of(clientOptions.headers(requestOptions)))
                      .addHeader("Accept", "application/json");
                    Request okhttpRequest = _requestBuilder.build();
                    OkHttpClient client = clientOptions.httpClient();
                    if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                      client = clientOptions.httpClientWithTimeout(requestOptions);
                    }
                    try (Response response = client.newCall(okhttpRequest).execute()) {
                      ResponseBody responseBody = response.body();
                      String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                      if (response.isSuccessful()) {
                        return new TradewatchApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, new TypeReference<List<TradingHoursResponse>>() {}), response);
                      }
                      try {
                        if (response.code() == 422) {
                          throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                        }
                      }
                      catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                      }
                      Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                      throw new TradewatchApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
                    }
                    catch (IOException e) {
                      throw new TradewatchApiException("Network error executing HTTP request", e);
                    }
                  }

                  /**
                   * Get market holidays. It takes half-days into account.
                   */
                  public TradewatchApiHttpResponse<List<MarketHolidayResponse>> getMarketHolidays(
                      StocksGetMarketHolidaysRequest request) {
                    return getMarketHolidays(request,null);
                  }

                  /**
                   * Get market holidays. It takes half-days into account.
                   */
                  public TradewatchApiHttpResponse<List<MarketHolidayResponse>> getMarketHolidays(
                      StocksGetMarketHolidaysRequest request, RequestOptions requestOptions) {
                    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

                      .addPathSegments("stocks/markets/holidays");if (request.getMic().isPresent()) {
                        QueryStringMapper.addQueryParameter(httpUrl, "mic", request.getMic().get(), false);
                      }
                      QueryStringMapper.addQueryParameter(httpUrl, "start", request.getStart(), false);
                      QueryStringMapper.addQueryParameter(httpUrl, "end", request.getEnd(), false);
                      if (requestOptions != null) {
                        requestOptions.getQueryParameters().forEach((_key, _value) -> {
                          httpUrl.addQueryParameter(_key, _value);
                        } );
                      }
                      Request.Builder _requestBuilder = new Request.Builder()
                        .url(httpUrl.build())
                        .method("GET", null)
                        .headers(Headers.of(clientOptions.headers(requestOptions)))
                        .addHeader("Accept", "application/json");
                      Request okhttpRequest = _requestBuilder.build();
                      OkHttpClient client = clientOptions.httpClient();
                      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                        client = clientOptions.httpClientWithTimeout(requestOptions);
                      }
                      try (Response response = client.newCall(okhttpRequest).execute()) {
                        ResponseBody responseBody = response.body();
                        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                        if (response.isSuccessful()) {
                          return new TradewatchApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, new TypeReference<List<MarketHolidayResponse>>() {}), response);
                        }
                        try {
                          if (response.code() == 422) {
                            throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                          }
                        }
                        catch (JsonProcessingException ignored) {
                          // unable to map error response, throwing generic error
                        }
                        Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                        throw new TradewatchApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
                      }
                      catch (IOException e) {
                        throw new TradewatchApiException("Network error executing HTTP request", e);
                      }
                    }

                    public TradewatchApiHttpResponse<StockDataFlatResponse> getStockData(
                        String symbol) {
                      return getStockData(symbol,StocksGetStockDataRequest.builder().build());
                    }

                    public TradewatchApiHttpResponse<StockDataFlatResponse> getStockData(
                        String symbol, RequestOptions requestOptions) {
                      return getStockData(symbol,StocksGetStockDataRequest.builder().build(),requestOptions);
                    }

                    public TradewatchApiHttpResponse<StockDataFlatResponse> getStockData(
                        String symbol, StocksGetStockDataRequest request) {
                      return getStockData(symbol,request,null);
                    }

                    public TradewatchApiHttpResponse<StockDataFlatResponse> getStockData(
                        String symbol, StocksGetStockDataRequest request,
                        RequestOptions requestOptions) {
                      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

                        .addPathSegments("stocks")
                        .addPathSegment(symbol);if (requestOptions != null) {
                          requestOptions.getQueryParameters().forEach((_key, _value) -> {
                            httpUrl.addQueryParameter(_key, _value);
                          } );
                        }
                        Request.Builder _requestBuilder = new Request.Builder()
                          .url(httpUrl.build())
                          .method("GET", null)
                          .headers(Headers.of(clientOptions.headers(requestOptions)))
                          .addHeader("Accept", "application/json");
                        Request okhttpRequest = _requestBuilder.build();
                        OkHttpClient client = clientOptions.httpClient();
                        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                          client = clientOptions.httpClientWithTimeout(requestOptions);
                        }
                        try (Response response = client.newCall(okhttpRequest).execute()) {
                          ResponseBody responseBody = response.body();
                          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                          if (response.isSuccessful()) {
                            return new TradewatchApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, StockDataFlatResponse.class), response);
                          }
                          try {
                            if (response.code() == 422) {
                              throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                            }
                          }
                          catch (JsonProcessingException ignored) {
                            // unable to map error response, throwing generic error
                          }
                          Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                          throw new TradewatchApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
                        }
                        catch (IOException e) {
                          throw new TradewatchApiException("Network error executing HTTP request", e);
                        }
                      }

                      /**
                       * Get historical OHLC candles for a symbol in a selected resolution and time range.
                       */
                      public TradewatchApiHttpResponse<HistoricalOhlcResponse> getHistoricalOhlc(
                          String symbol, StocksGetHistoricalOhlcRequest request) {
                        return getHistoricalOhlc(symbol,request,null);
                      }

                      /**
                       * Get historical OHLC candles for a symbol in a selected resolution and time range.
                       */
                      public TradewatchApiHttpResponse<HistoricalOhlcResponse> getHistoricalOhlc(
                          String symbol, StocksGetHistoricalOhlcRequest request,
                          RequestOptions requestOptions) {
                        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

                          .addPathSegments("stocks")
                          .addPathSegment(symbol)
                          .addPathSegments("ohlc");QueryStringMapper.addQueryParameter(httpUrl, "resolution", request.getResolution(), false);
                          QueryStringMapper.addQueryParameter(httpUrl, "start", request.getStart(), false);
                          QueryStringMapper.addQueryParameter(httpUrl, "end", request.getEnd(), false);
                          if (requestOptions != null) {
                            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                              httpUrl.addQueryParameter(_key, _value);
                            } );
                          }
                          Request.Builder _requestBuilder = new Request.Builder()
                            .url(httpUrl.build())
                            .method("GET", null)
                            .headers(Headers.of(clientOptions.headers(requestOptions)))
                            .addHeader("Accept", "application/json");
                          Request okhttpRequest = _requestBuilder.build();
                          OkHttpClient client = clientOptions.httpClient();
                          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                            client = clientOptions.httpClientWithTimeout(requestOptions);
                          }
                          try (Response response = client.newCall(okhttpRequest).execute()) {
                            ResponseBody responseBody = response.body();
                            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                            if (response.isSuccessful()) {
                              return new TradewatchApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, HistoricalOhlcResponse.class), response);
                            }
                            try {
                              if (response.code() == 422) {
                                throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                              }
                            }
                            catch (JsonProcessingException ignored) {
                              // unable to map error response, throwing generic error
                            }
                            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                            throw new TradewatchApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
                          }
                          catch (IOException e) {
                            throw new TradewatchApiException("Network error executing HTTP request", e);
                          }
                        }

                        /**
                         * Get raw historical ticks for a symbol in a selected time range using cursor pagination.
                         */
                        public TradewatchApiHttpResponse<CursorPageTCustomizedHistoricalRawTick> getHistoricalTicks(
                            String symbol, StocksGetHistoricalTicksRequest request) {
                          return getHistoricalTicks(symbol,request,null);
                        }

                        /**
                         * Get raw historical ticks for a symbol in a selected time range using cursor pagination.
                         */
                        public TradewatchApiHttpResponse<CursorPageTCustomizedHistoricalRawTick> getHistoricalTicks(
                            String symbol, StocksGetHistoricalTicksRequest request,
                            RequestOptions requestOptions) {
                          HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

                            .addPathSegments("stocks")
                            .addPathSegment(symbol)
                            .addPathSegments("ticks");QueryStringMapper.addQueryParameter(httpUrl, "start", request.getStart(), false);
                            QueryStringMapper.addQueryParameter(httpUrl, "end", request.getEnd(), false);
                            if (request.getCursor().isPresent()) {
                              QueryStringMapper.addQueryParameter(httpUrl, "cursor", request.getCursor().get(), false);
                            }
                            if (request.getLimit().isPresent()) {
                              QueryStringMapper.addQueryParameter(httpUrl, "limit", request.getLimit().get(), false);
                            }
                            if (requestOptions != null) {
                              requestOptions.getQueryParameters().forEach((_key, _value) -> {
                                httpUrl.addQueryParameter(_key, _value);
                              } );
                            }
                            Request.Builder _requestBuilder = new Request.Builder()
                              .url(httpUrl.build())
                              .method("GET", null)
                              .headers(Headers.of(clientOptions.headers(requestOptions)))
                              .addHeader("Accept", "application/json");
                            Request okhttpRequest = _requestBuilder.build();
                            OkHttpClient client = clientOptions.httpClient();
                            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                              client = clientOptions.httpClientWithTimeout(requestOptions);
                            }
                            try (Response response = client.newCall(okhttpRequest).execute()) {
                              ResponseBody responseBody = response.body();
                              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                              if (response.isSuccessful()) {
                                return new TradewatchApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, CursorPageTCustomizedHistoricalRawTick.class), response);
                              }
                              try {
                                if (response.code() == 422) {
                                  throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                                }
                              }
                              catch (JsonProcessingException ignored) {
                                // unable to map error response, throwing generic error
                              }
                              Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                              throw new TradewatchApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
                            }
                            catch (IOException e) {
                              throw new TradewatchApiException("Network error executing HTTP request", e);
                            }
                          }
                        }
