/*
 * tradewatch.io
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tradewatch.client.api;

import io.tradewatch.client.ApiException;
import io.tradewatch.client.model.AccountUsageStatisticsInterval;
import io.tradewatch.client.model.ErrorResponseBody;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountApi
 */
@Disabled
public class AccountApiTest {

    private final AccountApi api = new AccountApi();

    /**
     * Usage statistics
     *
     * Get the usage statistics of your API account
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getUsageTest() throws ApiException {
        Integer limit = null;
        AccountUsageStatisticsInterval interval = null;
        Object response = api.getUsage(limit, interval);
        // TODO: test validations
    }

}
