/*
 * tradewatch.io
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tradewatch.client.api;

import io.tradewatch.client.ApiException;
import io.tradewatch.client.model.CountriesList;
import io.tradewatch.client.model.Country;
import io.tradewatch.client.model.CursorPageTCustomizedSymbolsOutFull;
import io.tradewatch.client.model.HTTPValidationError;
import io.tradewatch.client.model.LastQuote;
import io.tradewatch.client.model.SymbolsListMode;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StocksApi
 */
@Disabled
public class StocksApiTest {

    private final StocksApi api = new StocksApi();

    /**
     * Available Countries
     *
     * Get list of available countries
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCountriesTest() throws ApiException {
        CountriesList response = api.getCountries();
        // TODO: test validations
    }

    /**
     * Last Quote
     *
     * Get the last quote tick for the provided symbol.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getQuoteTest() throws ApiException {
        String symbol = null;
        Integer precision = null;
        LastQuote response = api.getQuote(symbol, precision);
        // TODO: test validations
    }

    /**
     * Available Symbols
     *
     * Get list of available symbols
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSymbolsTest() throws ApiException {
        SymbolsListMode mode = null;
        Integer size = null;
        Country country = null;
        Integer page = null;
        String cursor = null;
        CursorPageTCustomizedSymbolsOutFull response = api.getSymbols(mode, size, country, page, cursor);
        // TODO: test validations
    }

}
