/**
 * This file was auto-generated by Fern from our API Definition.
 */

package io.tradewatch.client.resources.account;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import io.tradewatch.client.core.ClientOptions;
import io.tradewatch.client.core.ObjectMappers;
import io.tradewatch.client.core.QueryStringMapper;
import io.tradewatch.client.core.RequestOptions;
import io.tradewatch.client.core.TradewatchApiApiException;
import io.tradewatch.client.core.TradewatchApiException;
import io.tradewatch.client.core.TradewatchApiHttpResponse;
import io.tradewatch.client.errors.UnprocessableEntityError;
import io.tradewatch.client.resources.account.requests.AccountGetUsageRequest;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawAccountClient {
  protected final ClientOptions clientOptions;

  public AsyncRawAccountClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Get the usage statistics of your API account
   */
  public CompletableFuture<TradewatchApiHttpResponse<Map<String, Object>>> getUsage() {
    return getUsage(AccountGetUsageRequest.builder().build());
  }

  /**
   * Get the usage statistics of your API account
   */
  public CompletableFuture<TradewatchApiHttpResponse<Map<String, Object>>> getUsage(
      RequestOptions requestOptions) {
    return getUsage(AccountGetUsageRequest.builder().build(),requestOptions);
  }

  /**
   * Get the usage statistics of your API account
   */
  public CompletableFuture<TradewatchApiHttpResponse<Map<String, Object>>> getUsage(
      AccountGetUsageRequest request) {
    return getUsage(request,null);
  }

  /**
   * Get the usage statistics of your API account
   */
  public CompletableFuture<TradewatchApiHttpResponse<Map<String, Object>>> getUsage(
      AccountGetUsageRequest request, RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("usage");if (request.getLimit().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "limit", request.getLimit().get(), false);
      }
      if (request.getInterval().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "interval", request.getInterval().get(), false);
      }
      if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      CompletableFuture<TradewatchApiHttpResponse<Map<String, Object>>> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
              future.complete(new TradewatchApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, new TypeReference<Map<String, Object>>() {}), response));
              return;
            }
            try {
              if (response.code() == 422) {
                future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            future.completeExceptionally(new TradewatchApiApiException("Error with status code " + response.code(), response.code(), errorBody, response));
            return;
          }
          catch (IOException e) {
            future.completeExceptionally(new TradewatchApiException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new TradewatchApiException("Network error executing HTTP request", e));
        }
      });
      return future;
    }
  }
