/**
 * This file was auto-generated by Fern from our API Definition.
 */

package io.tradewatch.client.resources.account;

import io.tradewatch.client.core.ClientOptions;
import io.tradewatch.client.core.RequestOptions;
import io.tradewatch.client.resources.account.requests.AccountGetUsageRequest;
import java.lang.Object;
import java.lang.String;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

public class AsyncAccountClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawAccountClient rawClient;

  public AsyncAccountClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawAccountClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawAccountClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Get the usage statistics of your API account
   */
  public CompletableFuture<Map<String, Object>> getUsage() {
    return this.rawClient.getUsage().thenApply(response -> response.body());
  }

  /**
   * Get the usage statistics of your API account
   */
  public CompletableFuture<Map<String, Object>> getUsage(RequestOptions requestOptions) {
    return this.rawClient.getUsage(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get the usage statistics of your API account
   */
  public CompletableFuture<Map<String, Object>> getUsage(AccountGetUsageRequest request) {
    return this.rawClient.getUsage(request).thenApply(response -> response.body());
  }

  /**
   * Get the usage statistics of your API account
   */
  public CompletableFuture<Map<String, Object>> getUsage(AccountGetUsageRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.getUsage(request, requestOptions).thenApply(response -> response.body());
  }
}
