/**
 * This file was auto-generated by Fern from our API Definition.
 */

package io.tradewatch.client.resources.currencies.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.tradewatch.client.core.ObjectMappers;
import java.lang.Double;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CurrenciesConvertRequest.Builder.class
)
public final class CurrenciesConvertRequest {
  private final Optional<Double> amount;

  private final Optional<Integer> precision;

  private final Map<String, Object> additionalProperties;

  private CurrenciesConvertRequest(Optional<Double> amount, Optional<Integer> precision,
      Map<String, Object> additionalProperties) {
    this.amount = amount;
    this.precision = precision;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The amount to be converted.
   */
  @JsonProperty("amount")
  public Optional<Double> getAmount() {
    return amount;
  }

  /**
   * @return The decimal precision of the result.
   */
  @JsonProperty("precision")
  public Optional<Integer> getPrecision() {
    return precision;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CurrenciesConvertRequest && equalTo((CurrenciesConvertRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CurrenciesConvertRequest other) {
    return amount.equals(other.amount) && precision.equals(other.precision);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.amount, this.precision);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Double> amount = Optional.empty();

    private Optional<Integer> precision = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(CurrenciesConvertRequest other) {
      amount(other.getAmount());
      precision(other.getPrecision());
      return this;
    }

    /**
     * <p>The amount to be converted.</p>
     */
    @JsonSetter(
        value = "amount",
        nulls = Nulls.SKIP
    )
    public Builder amount(Optional<Double> amount) {
      this.amount = amount;
      return this;
    }

    public Builder amount(Double amount) {
      this.amount = Optional.ofNullable(amount);
      return this;
    }

    /**
     * <p>The decimal precision of the result.</p>
     */
    @JsonSetter(
        value = "precision",
        nulls = Nulls.SKIP
    )
    public Builder precision(Optional<Integer> precision) {
      this.precision = precision;
      return this;
    }

    public Builder precision(Integer precision) {
      this.precision = Optional.ofNullable(precision);
      return this;
    }

    public CurrenciesConvertRequest build() {
      return new CurrenciesConvertRequest(amount, precision, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
