/**
 * This file was auto-generated by Fern from our API Definition.
 */

package io.tradewatch.client.resources.stocks.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.tradewatch.client.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = StocksGetTradingHoursRequest.Builder.class
)
public final class StocksGetTradingHoursRequest {
  private final Optional<String> mic;

  private final String start;

  private final String end;

  private final Map<String, Object> additionalProperties;

  private StocksGetTradingHoursRequest(Optional<String> mic, String start, String end,
      Map<String, Object> additionalProperties) {
    this.mic = mic;
    this.start = start;
    this.end = end;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Optional list of comma separated MIC codes for which market to show data for. All market will be included if MIC code is not specified.
   */
  @JsonProperty("mic")
  public Optional<String> getMic() {
    return mic;
  }

  /**
   * @return Show holidays starting at this date.
   */
  @JsonProperty("start")
  public String getStart() {
    return start;
  }

  /**
   * @return Show holidays until this date.
   */
  @JsonProperty("end")
  public String getEnd() {
    return end;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof StocksGetTradingHoursRequest && equalTo((StocksGetTradingHoursRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(StocksGetTradingHoursRequest other) {
    return mic.equals(other.mic) && start.equals(other.start) && end.equals(other.end);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.mic, this.start, this.end);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static StartStage builder() {
    return new Builder();
  }

  public interface StartStage {
    /**
     * <p>Show holidays starting at this date.</p>
     */
    EndStage start(@NotNull String start);

    Builder from(StocksGetTradingHoursRequest other);
  }

  public interface EndStage {
    /**
     * <p>Show holidays until this date.</p>
     */
    _FinalStage end(@NotNull String end);
  }

  public interface _FinalStage {
    StocksGetTradingHoursRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Optional list of comma separated MIC codes for which market to show data for. All market will be included if MIC code is not specified.</p>
     */
    _FinalStage mic(Optional<String> mic);

    _FinalStage mic(String mic);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements StartStage, EndStage, _FinalStage {
    private String start;

    private String end;

    private Optional<String> mic = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(StocksGetTradingHoursRequest other) {
      mic(other.getMic());
      start(other.getStart());
      end(other.getEnd());
      return this;
    }

    /**
     * <p>Show holidays starting at this date.</p>
     * <p>Show holidays starting at this date.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("start")
    public EndStage start(@NotNull String start) {
      this.start = Objects.requireNonNull(start, "start must not be null");
      return this;
    }

    /**
     * <p>Show holidays until this date.</p>
     * <p>Show holidays until this date.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("end")
    public _FinalStage end(@NotNull String end) {
      this.end = Objects.requireNonNull(end, "end must not be null");
      return this;
    }

    /**
     * <p>Optional list of comma separated MIC codes for which market to show data for. All market will be included if MIC code is not specified.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage mic(String mic) {
      this.mic = Optional.ofNullable(mic);
      return this;
    }

    /**
     * <p>Optional list of comma separated MIC codes for which market to show data for. All market will be included if MIC code is not specified.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "mic",
        nulls = Nulls.SKIP
    )
    public _FinalStage mic(Optional<String> mic) {
      this.mic = mic;
      return this;
    }

    @java.lang.Override
    public StocksGetTradingHoursRequest build() {
      return new StocksGetTradingHoursRequest(mic, start, end, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
