/**
 * This file was auto-generated by Fern from our API Definition.
 */

package io.tradewatch.client.resources.stocks.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.tradewatch.client.core.ObjectMappers;
import io.tradewatch.client.types.HistoricalDataResolution;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = StocksGetHistoricalOhlcRequest.Builder.class
)
public final class StocksGetHistoricalOhlcRequest {
  private final HistoricalDataResolution resolution;

  private final int start;

  private final int end;

  private final Map<String, Object> additionalProperties;

  private StocksGetHistoricalOhlcRequest(HistoricalDataResolution resolution, int start, int end,
      Map<String, Object> additionalProperties) {
    this.resolution = resolution;
    this.start = start;
    this.end = end;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Resolution in seconds.
   */
  @JsonProperty("resolution")
  public HistoricalDataResolution getResolution() {
    return resolution;
  }

  /**
   * @return Unix timestamp (inclusive).
   */
  @JsonProperty("start")
  public int getStart() {
    return start;
  }

  /**
   * @return Unix timestamp (exclusive).
   */
  @JsonProperty("end")
  public int getEnd() {
    return end;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof StocksGetHistoricalOhlcRequest && equalTo((StocksGetHistoricalOhlcRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(StocksGetHistoricalOhlcRequest other) {
    return resolution.equals(other.resolution) && start == other.start && end == other.end;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.resolution, this.start, this.end);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ResolutionStage builder() {
    return new Builder();
  }

  public interface ResolutionStage {
    /**
     * <p>Resolution in seconds.</p>
     */
    StartStage resolution(@NotNull HistoricalDataResolution resolution);

    Builder from(StocksGetHistoricalOhlcRequest other);
  }

  public interface StartStage {
    /**
     * <p>Unix timestamp (inclusive).</p>
     */
    EndStage start(int start);
  }

  public interface EndStage {
    /**
     * <p>Unix timestamp (exclusive).</p>
     */
    _FinalStage end(int end);
  }

  public interface _FinalStage {
    StocksGetHistoricalOhlcRequest build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements ResolutionStage, StartStage, EndStage, _FinalStage {
    private HistoricalDataResolution resolution;

    private int start;

    private int end;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(StocksGetHistoricalOhlcRequest other) {
      resolution(other.getResolution());
      start(other.getStart());
      end(other.getEnd());
      return this;
    }

    /**
     * <p>Resolution in seconds.</p>
     * <p>Resolution in seconds.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("resolution")
    public StartStage resolution(@NotNull HistoricalDataResolution resolution) {
      this.resolution = Objects.requireNonNull(resolution, "resolution must not be null");
      return this;
    }

    /**
     * <p>Unix timestamp (inclusive).</p>
     * <p>Unix timestamp (inclusive).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("start")
    public EndStage start(int start) {
      this.start = start;
      return this;
    }

    /**
     * <p>Unix timestamp (exclusive).</p>
     * <p>Unix timestamp (exclusive).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("end")
    public _FinalStage end(int end) {
      this.end = end;
      return this;
    }

    @java.lang.Override
    public StocksGetHistoricalOhlcRequest build() {
      return new StocksGetHistoricalOhlcRequest(resolution, start, end, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
