/**
 * This file was auto-generated by Fern from our API Definition.
 */

package io.tradewatch.client.resources.stocks.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.tradewatch.client.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = StocksGetMarketStatusRequest.Builder.class
)
public final class StocksGetMarketStatusRequest {
  private final Optional<String> mic;

  private final Map<String, Object> additionalProperties;

  private StocksGetMarketStatusRequest(Optional<String> mic,
      Map<String, Object> additionalProperties) {
    this.mic = mic;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Optional list of comma separated MIC codes for which market to show data for. All market will be included if MIC code is not specified.
   */
  @JsonProperty("mic")
  public Optional<String> getMic() {
    return mic;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof StocksGetMarketStatusRequest && equalTo((StocksGetMarketStatusRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(StocksGetMarketStatusRequest other) {
    return mic.equals(other.mic);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.mic);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> mic = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(StocksGetMarketStatusRequest other) {
      mic(other.getMic());
      return this;
    }

    /**
     * <p>Optional list of comma separated MIC codes for which market to show data for. All market will be included if MIC code is not specified.</p>
     */
    @JsonSetter(
        value = "mic",
        nulls = Nulls.SKIP
    )
    public Builder mic(Optional<String> mic) {
      this.mic = mic;
      return this;
    }

    public Builder mic(String mic) {
      this.mic = Optional.ofNullable(mic);
      return this;
    }

    public StocksGetMarketStatusRequest build() {
      return new StocksGetMarketStatusRequest(mic, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
