/**
 * This file was auto-generated by Fern from our API Definition.
 */

package io.tradewatch.client.resources.stocks.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.tradewatch.client.core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = StocksGetSymbolsRequest.Builder.class
)
public final class StocksGetSymbolsRequest {
  private final Optional<Integer> size;

  private final Optional<String> mode;

  private final Optional<String> type;

  private final Optional<String> country;

  private final Optional<String> cursor;

  private final Map<String, Object> additionalProperties;

  private StocksGetSymbolsRequest(Optional<Integer> size, Optional<String> mode,
      Optional<String> type, Optional<String> country, Optional<String> cursor,
      Map<String, Object> additionalProperties) {
    this.size = size;
    this.mode = mode;
    this.type = type;
    this.country = country;
    this.cursor = cursor;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The number of items per page.
   */
  @JsonProperty("size")
  public Optional<Integer> getSize() {
    return size;
  }

  /**
   * @return The mode of the response.
   */
  @JsonProperty("mode")
  public Optional<String> getMode() {
    return mode;
  }

  /**
   * @return Type of the instrument.
   */
  @JsonProperty("type")
  public Optional<String> getType() {
    return type;
  }

  /**
   * @return Country of the instrument.
   */
  @JsonProperty("country")
  public Optional<String> getCountry() {
    return country;
  }

  /**
   * @return Cursor for the next page
   */
  @JsonProperty("cursor")
  public Optional<String> getCursor() {
    return cursor;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof StocksGetSymbolsRequest && equalTo((StocksGetSymbolsRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(StocksGetSymbolsRequest other) {
    return size.equals(other.size) && mode.equals(other.mode) && type.equals(other.type) && country.equals(other.country) && cursor.equals(other.cursor);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.size, this.mode, this.type, this.country, this.cursor);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Integer> size = Optional.empty();

    private Optional<String> mode = Optional.empty();

    private Optional<String> type = Optional.empty();

    private Optional<String> country = Optional.empty();

    private Optional<String> cursor = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(StocksGetSymbolsRequest other) {
      size(other.getSize());
      mode(other.getMode());
      type(other.getType());
      country(other.getCountry());
      cursor(other.getCursor());
      return this;
    }

    /**
     * <p>The number of items per page.</p>
     */
    @JsonSetter(
        value = "size",
        nulls = Nulls.SKIP
    )
    public Builder size(Optional<Integer> size) {
      this.size = size;
      return this;
    }

    public Builder size(Integer size) {
      this.size = Optional.ofNullable(size);
      return this;
    }

    /**
     * <p>The mode of the response.</p>
     */
    @JsonSetter(
        value = "mode",
        nulls = Nulls.SKIP
    )
    public Builder mode(Optional<String> mode) {
      this.mode = mode;
      return this;
    }

    public Builder mode(String mode) {
      this.mode = Optional.ofNullable(mode);
      return this;
    }

    /**
     * <p>Type of the instrument.</p>
     */
    @JsonSetter(
        value = "type",
        nulls = Nulls.SKIP
    )
    public Builder type(Optional<String> type) {
      this.type = type;
      return this;
    }

    public Builder type(String type) {
      this.type = Optional.ofNullable(type);
      return this;
    }

    /**
     * <p>Country of the instrument.</p>
     */
    @JsonSetter(
        value = "country",
        nulls = Nulls.SKIP
    )
    public Builder country(Optional<String> country) {
      this.country = country;
      return this;
    }

    public Builder country(String country) {
      this.country = Optional.ofNullable(country);
      return this;
    }

    /**
     * <p>Cursor for the next page</p>
     */
    @JsonSetter(
        value = "cursor",
        nulls = Nulls.SKIP
    )
    public Builder cursor(Optional<String> cursor) {
      this.cursor = cursor;
      return this;
    }

    public Builder cursor(String cursor) {
      this.cursor = Optional.ofNullable(cursor);
      return this;
    }

    public StocksGetSymbolsRequest build() {
      return new StocksGetSymbolsRequest(size, mode, type, country, cursor, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
