/**
 * This file was auto-generated by Fern from our API Definition.
 */

package io.tradewatch.client.resources.account.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.tradewatch.client.core.ObjectMappers;
import io.tradewatch.client.types.AccountUsageStatisticsInterval;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = AccountGetUsageRequest.Builder.class
)
public final class AccountGetUsageRequest {
  private final Optional<Integer> limit;

  private final Optional<AccountUsageStatisticsInterval> interval;

  private final Map<String, Object> additionalProperties;

  private AccountGetUsageRequest(Optional<Integer> limit,
      Optional<AccountUsageStatisticsInterval> interval, Map<String, Object> additionalProperties) {
    this.limit = limit;
    this.interval = interval;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return The number of data points to return (max 168).
   */
  @JsonProperty("limit")
  public Optional<Integer> getLimit() {
    return limit;
  }

  /**
   * @return The time interval for the usage statistics.
   */
  @JsonProperty("interval")
  public Optional<AccountUsageStatisticsInterval> getInterval() {
    return interval;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof AccountGetUsageRequest && equalTo((AccountGetUsageRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(AccountGetUsageRequest other) {
    return limit.equals(other.limit) && interval.equals(other.interval);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.limit, this.interval);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Integer> limit = Optional.empty();

    private Optional<AccountUsageStatisticsInterval> interval = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(AccountGetUsageRequest other) {
      limit(other.getLimit());
      interval(other.getInterval());
      return this;
    }

    /**
     * <p>The number of data points to return (max 168).</p>
     */
    @JsonSetter(
        value = "limit",
        nulls = Nulls.SKIP
    )
    public Builder limit(Optional<Integer> limit) {
      this.limit = limit;
      return this;
    }

    public Builder limit(Integer limit) {
      this.limit = Optional.ofNullable(limit);
      return this;
    }

    /**
     * <p>The time interval for the usage statistics.</p>
     */
    @JsonSetter(
        value = "interval",
        nulls = Nulls.SKIP
    )
    public Builder interval(Optional<AccountUsageStatisticsInterval> interval) {
      this.interval = interval;
      return this;
    }

    public Builder interval(AccountUsageStatisticsInterval interval) {
      this.interval = Optional.ofNullable(interval);
      return this;
    }

    public AccountGetUsageRequest build() {
      return new AccountGetUsageRequest(limit, interval, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
