/**
 * This file was auto-generated by Fern from our API Definition.
 */

package io.tradewatch.client.resources.indices;

import io.tradewatch.client.core.ClientOptions;
import io.tradewatch.client.core.RequestOptions;
import io.tradewatch.client.resources.indices.requests.IndicesGetInsightsRequest;
import io.tradewatch.client.resources.indices.requests.IndicesGetQuoteRequest;
import io.tradewatch.client.resources.indices.requests.IndicesGetQuotesRequest;
import io.tradewatch.client.resources.indices.requests.IndicesGetSymbolsRequest;
import io.tradewatch.client.types.CursorPageTCustomizedNewsOut;
import io.tradewatch.client.types.CursorPageTCustomizedSymbolsOutFull;
import io.tradewatch.client.types.LastQuote;
import io.tradewatch.client.types.LastQuotes;
import java.util.concurrent.CompletableFuture;

public class AsyncIndicesClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawIndicesClient rawClient;

  public AsyncIndicesClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawIndicesClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawIndicesClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Get the last quote tick for the provided symbols.
   */
  public CompletableFuture<LastQuotes> getQuotes(IndicesGetQuotesRequest request) {
    return this.rawClient.getQuotes(request).thenApply(response -> response.body());
  }

  /**
   * Get the last quote tick for the provided symbols.
   */
  public CompletableFuture<LastQuotes> getQuotes(IndicesGetQuotesRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.getQuotes(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get the last quote tick for the provided symbol.
   */
  public CompletableFuture<LastQuote> getQuote(IndicesGetQuoteRequest request) {
    return this.rawClient.getQuote(request).thenApply(response -> response.body());
  }

  /**
   * Get the last quote tick for the provided symbol.
   */
  public CompletableFuture<LastQuote> getQuote(IndicesGetQuoteRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.getQuote(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get list of available symbols
   */
  public CompletableFuture<CursorPageTCustomizedSymbolsOutFull> getSymbols() {
    return this.rawClient.getSymbols().thenApply(response -> response.body());
  }

  /**
   * Get list of available symbols
   */
  public CompletableFuture<CursorPageTCustomizedSymbolsOutFull> getSymbols(
      RequestOptions requestOptions) {
    return this.rawClient.getSymbols(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get list of available symbols
   */
  public CompletableFuture<CursorPageTCustomizedSymbolsOutFull> getSymbols(
      IndicesGetSymbolsRequest request) {
    return this.rawClient.getSymbols(request).thenApply(response -> response.body());
  }

  /**
   * Get list of available symbols
   */
  public CompletableFuture<CursorPageTCustomizedSymbolsOutFull> getSymbols(
      IndicesGetSymbolsRequest request, RequestOptions requestOptions) {
    return this.rawClient.getSymbols(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get recent indices insights.
   */
  public CompletableFuture<CursorPageTCustomizedNewsOut> getInsights() {
    return this.rawClient.getInsights().thenApply(response -> response.body());
  }

  /**
   * Get recent indices insights.
   */
  public CompletableFuture<CursorPageTCustomizedNewsOut> getInsights(
      RequestOptions requestOptions) {
    return this.rawClient.getInsights(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get recent indices insights.
   */
  public CompletableFuture<CursorPageTCustomizedNewsOut> getInsights(
      IndicesGetInsightsRequest request) {
    return this.rawClient.getInsights(request).thenApply(response -> response.body());
  }

  /**
   * Get recent indices insights.
   */
  public CompletableFuture<CursorPageTCustomizedNewsOut> getInsights(
      IndicesGetInsightsRequest request, RequestOptions requestOptions) {
    return this.rawClient.getInsights(request, requestOptions).thenApply(response -> response.body());
  }
}
