/**
 * This file was auto-generated by Fern from our API Definition.
 */

package io.tradewatch.client.resources.indices;

import io.tradewatch.client.core.ClientOptions;
import io.tradewatch.client.core.RequestOptions;
import io.tradewatch.client.resources.indices.requests.IndicesGetInsightsRequest;
import io.tradewatch.client.resources.indices.requests.IndicesGetQuoteRequest;
import io.tradewatch.client.resources.indices.requests.IndicesGetQuotesRequest;
import io.tradewatch.client.resources.indices.requests.IndicesGetSymbolsRequest;
import io.tradewatch.client.types.CursorPageTCustomizedNewsOut;
import io.tradewatch.client.types.CursorPageTCustomizedSymbolsOutFull;
import io.tradewatch.client.types.LastQuote;
import io.tradewatch.client.types.LastQuotes;

public class IndicesClient {
  protected final ClientOptions clientOptions;

  private final RawIndicesClient rawClient;

  public IndicesClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new RawIndicesClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public RawIndicesClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Get the last quote tick for the provided symbols.
   */
  public LastQuotes getQuotes(IndicesGetQuotesRequest request) {
    return this.rawClient.getQuotes(request).body();
  }

  /**
   * Get the last quote tick for the provided symbols.
   */
  public LastQuotes getQuotes(IndicesGetQuotesRequest request, RequestOptions requestOptions) {
    return this.rawClient.getQuotes(request, requestOptions).body();
  }

  /**
   * Get the last quote tick for the provided symbol.
   */
  public LastQuote getQuote(IndicesGetQuoteRequest request) {
    return this.rawClient.getQuote(request).body();
  }

  /**
   * Get the last quote tick for the provided symbol.
   */
  public LastQuote getQuote(IndicesGetQuoteRequest request, RequestOptions requestOptions) {
    return this.rawClient.getQuote(request, requestOptions).body();
  }

  /**
   * Get list of available symbols
   */
  public CursorPageTCustomizedSymbolsOutFull getSymbols() {
    return this.rawClient.getSymbols().body();
  }

  /**
   * Get list of available symbols
   */
  public CursorPageTCustomizedSymbolsOutFull getSymbols(RequestOptions requestOptions) {
    return this.rawClient.getSymbols(requestOptions).body();
  }

  /**
   * Get list of available symbols
   */
  public CursorPageTCustomizedSymbolsOutFull getSymbols(IndicesGetSymbolsRequest request) {
    return this.rawClient.getSymbols(request).body();
  }

  /**
   * Get list of available symbols
   */
  public CursorPageTCustomizedSymbolsOutFull getSymbols(IndicesGetSymbolsRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.getSymbols(request, requestOptions).body();
  }

  /**
   * Get recent indices insights.
   */
  public CursorPageTCustomizedNewsOut getInsights() {
    return this.rawClient.getInsights().body();
  }

  /**
   * Get recent indices insights.
   */
  public CursorPageTCustomizedNewsOut getInsights(RequestOptions requestOptions) {
    return this.rawClient.getInsights(requestOptions).body();
  }

  /**
   * Get recent indices insights.
   */
  public CursorPageTCustomizedNewsOut getInsights(IndicesGetInsightsRequest request) {
    return this.rawClient.getInsights(request).body();
  }

  /**
   * Get recent indices insights.
   */
  public CursorPageTCustomizedNewsOut getInsights(IndicesGetInsightsRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.getInsights(request, requestOptions).body();
  }
}
