/**
 * This file was auto-generated by Fern from our API Definition.
 */

package io.tradewatch.client;

import io.tradewatch.client.core.ClientOptions;
import io.tradewatch.client.core.Suppliers;
import io.tradewatch.client.resources.account.AsyncAccountClient;
import io.tradewatch.client.resources.commodities.AsyncCommoditiesClient;
import io.tradewatch.client.resources.crypto.AsyncCryptoClient;
import io.tradewatch.client.resources.currencies.AsyncCurrenciesClient;
import io.tradewatch.client.resources.indices.AsyncIndicesClient;
import io.tradewatch.client.resources.stocks.AsyncStocksClient;
import java.util.function.Supplier;

public class AsyncTradewatchApiClient {
  protected final ClientOptions clientOptions;

  protected final Supplier<AsyncAccountClient> accountClient;

  protected final Supplier<AsyncCurrenciesClient> currenciesClient;

  protected final Supplier<AsyncCryptoClient> cryptoClient;

  protected final Supplier<AsyncIndicesClient> indicesClient;

  protected final Supplier<AsyncStocksClient> stocksClient;

  protected final Supplier<AsyncCommoditiesClient> commoditiesClient;

  public AsyncTradewatchApiClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.accountClient = Suppliers.memoize(() -> new AsyncAccountClient(clientOptions));
    this.currenciesClient = Suppliers.memoize(() -> new AsyncCurrenciesClient(clientOptions));
    this.cryptoClient = Suppliers.memoize(() -> new AsyncCryptoClient(clientOptions));
    this.indicesClient = Suppliers.memoize(() -> new AsyncIndicesClient(clientOptions));
    this.stocksClient = Suppliers.memoize(() -> new AsyncStocksClient(clientOptions));
    this.commoditiesClient = Suppliers.memoize(() -> new AsyncCommoditiesClient(clientOptions));
  }

  public AsyncAccountClient account() {
    return this.accountClient.get();
  }

  public AsyncCurrenciesClient currencies() {
    return this.currenciesClient.get();
  }

  public AsyncCryptoClient crypto() {
    return this.cryptoClient.get();
  }

  public AsyncIndicesClient indices() {
    return this.indicesClient.get();
  }

  public AsyncStocksClient stocks() {
    return this.stocksClient.get();
  }

  public AsyncCommoditiesClient commodities() {
    return this.commoditiesClient.get();
  }

  public static AsyncTradewatchApiClientBuilder builder() {
    return new AsyncTradewatchApiClientBuilder();
  }
}
