/**
 * This file was auto-generated by Fern from our API Definition.
 */

package io.tradewatch.client.resources.crypto;

import io.tradewatch.client.core.ClientOptions;
import io.tradewatch.client.core.RequestOptions;
import io.tradewatch.client.resources.crypto.requests.CryptoConvertRequest;
import io.tradewatch.client.resources.crypto.requests.CryptoGetInsightsRequest;
import io.tradewatch.client.resources.crypto.requests.CryptoGetQuoteRequest;
import io.tradewatch.client.resources.crypto.requests.CryptoGetQuotesRequest;
import io.tradewatch.client.resources.crypto.requests.CryptoGetSymbolsRequest;
import io.tradewatch.client.types.CryptoConversion;
import io.tradewatch.client.types.CryptoExchangesList;
import io.tradewatch.client.types.CursorPageTCustomizedNewsOut;
import io.tradewatch.client.types.CursorPageTCustomizedSymbolsOutFull;
import io.tradewatch.client.types.LastQuote;
import io.tradewatch.client.types.LastQuotes;
import java.lang.String;
import java.util.concurrent.CompletableFuture;

public class AsyncCryptoClient {
  protected final ClientOptions clientOptions;

  private final AsyncRawCryptoClient rawClient;

  public AsyncCryptoClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new AsyncRawCryptoClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public AsyncRawCryptoClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Convert one symbol to another
   */
  public CompletableFuture<CryptoConversion> convert(String from, String to) {
    return this.rawClient.convert(from, to).thenApply(response -> response.body());
  }

  /**
   * Convert one symbol to another
   */
  public CompletableFuture<CryptoConversion> convert(String from, String to,
      RequestOptions requestOptions) {
    return this.rawClient.convert(from, to, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Convert one symbol to another
   */
  public CompletableFuture<CryptoConversion> convert(String from, String to,
      CryptoConvertRequest request) {
    return this.rawClient.convert(from, to, request).thenApply(response -> response.body());
  }

  /**
   * Convert one symbol to another
   */
  public CompletableFuture<CryptoConversion> convert(String from, String to,
      CryptoConvertRequest request, RequestOptions requestOptions) {
    return this.rawClient.convert(from, to, request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get list of available cryptocurrency exchanges
   */
  public CompletableFuture<CryptoExchangesList> getExchanges() {
    return this.rawClient.getExchanges().thenApply(response -> response.body());
  }

  /**
   * Get list of available cryptocurrency exchanges
   */
  public CompletableFuture<CryptoExchangesList> getExchanges(RequestOptions requestOptions) {
    return this.rawClient.getExchanges(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get the last quote tick for the provided symbols.
   */
  public CompletableFuture<LastQuotes> getQuotes(CryptoGetQuotesRequest request) {
    return this.rawClient.getQuotes(request).thenApply(response -> response.body());
  }

  /**
   * Get the last quote tick for the provided symbols.
   */
  public CompletableFuture<LastQuotes> getQuotes(CryptoGetQuotesRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.getQuotes(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get the last quote tick for the provided symbol.
   */
  public CompletableFuture<LastQuote> getQuote(CryptoGetQuoteRequest request) {
    return this.rawClient.getQuote(request).thenApply(response -> response.body());
  }

  /**
   * Get the last quote tick for the provided symbol.
   */
  public CompletableFuture<LastQuote> getQuote(CryptoGetQuoteRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.getQuote(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get list of available symbols
   */
  public CompletableFuture<CursorPageTCustomizedSymbolsOutFull> getSymbols() {
    return this.rawClient.getSymbols().thenApply(response -> response.body());
  }

  /**
   * Get list of available symbols
   */
  public CompletableFuture<CursorPageTCustomizedSymbolsOutFull> getSymbols(
      RequestOptions requestOptions) {
    return this.rawClient.getSymbols(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get list of available symbols
   */
  public CompletableFuture<CursorPageTCustomizedSymbolsOutFull> getSymbols(
      CryptoGetSymbolsRequest request) {
    return this.rawClient.getSymbols(request).thenApply(response -> response.body());
  }

  /**
   * Get list of available symbols
   */
  public CompletableFuture<CursorPageTCustomizedSymbolsOutFull> getSymbols(
      CryptoGetSymbolsRequest request, RequestOptions requestOptions) {
    return this.rawClient.getSymbols(request, requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get recent crypto insights.
   */
  public CompletableFuture<CursorPageTCustomizedNewsOut> getInsights() {
    return this.rawClient.getInsights().thenApply(response -> response.body());
  }

  /**
   * Get recent crypto insights.
   */
  public CompletableFuture<CursorPageTCustomizedNewsOut> getInsights(
      RequestOptions requestOptions) {
    return this.rawClient.getInsights(requestOptions).thenApply(response -> response.body());
  }

  /**
   * Get recent crypto insights.
   */
  public CompletableFuture<CursorPageTCustomizedNewsOut> getInsights(
      CryptoGetInsightsRequest request) {
    return this.rawClient.getInsights(request).thenApply(response -> response.body());
  }

  /**
   * Get recent crypto insights.
   */
  public CompletableFuture<CursorPageTCustomizedNewsOut> getInsights(
      CryptoGetInsightsRequest request, RequestOptions requestOptions) {
    return this.rawClient.getInsights(request, requestOptions).thenApply(response -> response.body());
  }
}
