/**
 * This file was auto-generated by Fern from our API Definition.
 */

package io.tradewatch.client.resources.crypto;

import com.fasterxml.jackson.core.JsonProcessingException;
import io.tradewatch.client.core.ClientOptions;
import io.tradewatch.client.core.ObjectMappers;
import io.tradewatch.client.core.QueryStringMapper;
import io.tradewatch.client.core.RequestOptions;
import io.tradewatch.client.core.TradewatchApiApiException;
import io.tradewatch.client.core.TradewatchApiException;
import io.tradewatch.client.core.TradewatchApiHttpResponse;
import io.tradewatch.client.errors.UnprocessableEntityError;
import io.tradewatch.client.resources.crypto.requests.CryptoConvertRequest;
import io.tradewatch.client.resources.crypto.requests.CryptoGetInsightsRequest;
import io.tradewatch.client.resources.crypto.requests.CryptoGetQuoteRequest;
import io.tradewatch.client.resources.crypto.requests.CryptoGetQuotesRequest;
import io.tradewatch.client.resources.crypto.requests.CryptoGetSymbolsRequest;
import io.tradewatch.client.types.CryptoConversion;
import io.tradewatch.client.types.CryptoExchangesList;
import io.tradewatch.client.types.CursorPageTCustomizedNewsOut;
import io.tradewatch.client.types.CursorPageTCustomizedSymbolsOutFull;
import io.tradewatch.client.types.LastQuote;
import io.tradewatch.client.types.LastQuotes;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawCryptoClient {
  protected final ClientOptions clientOptions;

  public AsyncRawCryptoClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Convert one symbol to another
   */
  public CompletableFuture<TradewatchApiHttpResponse<CryptoConversion>> convert(String from,
      String to) {
    return convert(from,to,CryptoConvertRequest.builder().build());
  }

  /**
   * Convert one symbol to another
   */
  public CompletableFuture<TradewatchApiHttpResponse<CryptoConversion>> convert(String from,
      String to, RequestOptions requestOptions) {
    return convert(from,to,CryptoConvertRequest.builder().build(),requestOptions);
  }

  /**
   * Convert one symbol to another
   */
  public CompletableFuture<TradewatchApiHttpResponse<CryptoConversion>> convert(String from,
      String to, CryptoConvertRequest request) {
    return convert(from,to,request,null);
  }

  /**
   * Convert one symbol to another
   */
  public CompletableFuture<TradewatchApiHttpResponse<CryptoConversion>> convert(String from,
      String to, CryptoConvertRequest request, RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("crypto/convert")
      .addPathSegment(from)
      .addPathSegment(to);if (request.getAmount().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "amount", request.getAmount().get(), false);
      }
      if (request.getPrecision().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "precision", request.getPrecision().get(), false);
      }
      if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      CompletableFuture<TradewatchApiHttpResponse<CryptoConversion>> future = new CompletableFuture<>();
      client.newCall(okhttpRequest).enqueue(new Callback() {
        @Override
        public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
          try (ResponseBody responseBody = response.body()) {
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
              future.complete(new TradewatchApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, CryptoConversion.class), response));
              return;
            }
            try {
              if (response.code() == 422) {
                future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                return;
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            future.completeExceptionally(new TradewatchApiApiException("Error with status code " + response.code(), response.code(), errorBody, response));
            return;
          }
          catch (IOException e) {
            future.completeExceptionally(new TradewatchApiException("Network error executing HTTP request", e));
          }
        }

        @Override
        public void onFailure(@NotNull Call call, @NotNull IOException e) {
          future.completeExceptionally(new TradewatchApiException("Network error executing HTTP request", e));
        }
      });
      return future;
    }

    /**
     * Get list of available cryptocurrency exchanges
     */
    public CompletableFuture<TradewatchApiHttpResponse<CryptoExchangesList>> getExchanges() {
      return getExchanges(null);
    }

    /**
     * Get list of available cryptocurrency exchanges
     */
    public CompletableFuture<TradewatchApiHttpResponse<CryptoExchangesList>> getExchanges(
        RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("crypto/exchanges");if (requestOptions != null) {
          requestOptions.getQueryParameters().forEach((_key, _value) -> {
            httpUrl.addQueryParameter(_key, _value);
          } );
        }
        Request okhttpRequest = new Request.Builder()
          .url(httpUrl.build())
          .method("GET", null)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Accept", "application/json")
          .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<TradewatchApiHttpResponse<CryptoExchangesList>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
          @Override
          public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
            try (ResponseBody responseBody = response.body()) {
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              if (response.isSuccessful()) {
                future.complete(new TradewatchApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, CryptoExchangesList.class), response));
                return;
              }
              Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
              future.completeExceptionally(new TradewatchApiApiException("Error with status code " + response.code(), response.code(), errorBody, response));
              return;
            }
            catch (IOException e) {
              future.completeExceptionally(new TradewatchApiException("Network error executing HTTP request", e));
            }
          }

          @Override
          public void onFailure(@NotNull Call call, @NotNull IOException e) {
            future.completeExceptionally(new TradewatchApiException("Network error executing HTTP request", e));
          }
        });
        return future;
      }

      /**
       * Get the last quote tick for the provided symbols.
       */
      public CompletableFuture<TradewatchApiHttpResponse<LastQuotes>> getQuotes(
          CryptoGetQuotesRequest request) {
        return getQuotes(request,null);
      }

      /**
       * Get the last quote tick for the provided symbols.
       */
      public CompletableFuture<TradewatchApiHttpResponse<LastQuotes>> getQuotes(
          CryptoGetQuotesRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("crypto/quotes");QueryStringMapper.addQueryParameter(httpUrl, "symbols", request.getSymbols(), false);
          if (request.getPrecision().isPresent()) {
            QueryStringMapper.addQueryParameter(httpUrl, "precision", request.getPrecision().get(), false);
          }
          if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
              httpUrl.addQueryParameter(_key, _value);
            } );
          }
          Request.Builder _requestBuilder = new Request.Builder()
            .url(httpUrl.build())
            .method("GET", null)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Accept", "application/json");
          Request okhttpRequest = _requestBuilder.build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          CompletableFuture<TradewatchApiHttpResponse<LastQuotes>> future = new CompletableFuture<>();
          client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
              try (ResponseBody responseBody = response.body()) {
                String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                if (response.isSuccessful()) {
                  future.complete(new TradewatchApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, LastQuotes.class), response));
                  return;
                }
                try {
                  if (response.code() == 422) {
                    future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                    return;
                  }
                }
                catch (JsonProcessingException ignored) {
                  // unable to map error response, throwing generic error
                }
                Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                future.completeExceptionally(new TradewatchApiApiException("Error with status code " + response.code(), response.code(), errorBody, response));
                return;
              }
              catch (IOException e) {
                future.completeExceptionally(new TradewatchApiException("Network error executing HTTP request", e));
              }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
              future.completeExceptionally(new TradewatchApiException("Network error executing HTTP request", e));
            }
          });
          return future;
        }

        /**
         * Get the last quote tick for the provided symbol.
         */
        public CompletableFuture<TradewatchApiHttpResponse<LastQuote>> getQuote(
            CryptoGetQuoteRequest request) {
          return getQuote(request,null);
        }

        /**
         * Get the last quote tick for the provided symbol.
         */
        public CompletableFuture<TradewatchApiHttpResponse<LastQuote>> getQuote(
            CryptoGetQuoteRequest request, RequestOptions requestOptions) {
          HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

            .addPathSegments("crypto/quote");QueryStringMapper.addQueryParameter(httpUrl, "symbol", request.getSymbol(), false);
            if (request.getPrecision().isPresent()) {
              QueryStringMapper.addQueryParameter(httpUrl, "precision", request.getPrecision().get(), false);
            }
            if (requestOptions != null) {
              requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
              } );
            }
            Request.Builder _requestBuilder = new Request.Builder()
              .url(httpUrl.build())
              .method("GET", null)
              .headers(Headers.of(clientOptions.headers(requestOptions)))
              .addHeader("Accept", "application/json");
            Request okhttpRequest = _requestBuilder.build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            CompletableFuture<TradewatchApiHttpResponse<LastQuote>> future = new CompletableFuture<>();
            client.newCall(okhttpRequest).enqueue(new Callback() {
              @Override
              public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                  String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                  if (response.isSuccessful()) {
                    future.complete(new TradewatchApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, LastQuote.class), response));
                    return;
                  }
                  try {
                    if (response.code() == 422) {
                      future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                      return;
                    }
                  }
                  catch (JsonProcessingException ignored) {
                    // unable to map error response, throwing generic error
                  }
                  Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                  future.completeExceptionally(new TradewatchApiApiException("Error with status code " + response.code(), response.code(), errorBody, response));
                  return;
                }
                catch (IOException e) {
                  future.completeExceptionally(new TradewatchApiException("Network error executing HTTP request", e));
                }
              }

              @Override
              public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new TradewatchApiException("Network error executing HTTP request", e));
              }
            });
            return future;
          }

          /**
           * Get list of available symbols
           */
          public CompletableFuture<TradewatchApiHttpResponse<CursorPageTCustomizedSymbolsOutFull>> getSymbols(
              ) {
            return getSymbols(CryptoGetSymbolsRequest.builder().build());
          }

          /**
           * Get list of available symbols
           */
          public CompletableFuture<TradewatchApiHttpResponse<CursorPageTCustomizedSymbolsOutFull>> getSymbols(
              RequestOptions requestOptions) {
            return getSymbols(CryptoGetSymbolsRequest.builder().build(),requestOptions);
          }

          /**
           * Get list of available symbols
           */
          public CompletableFuture<TradewatchApiHttpResponse<CursorPageTCustomizedSymbolsOutFull>> getSymbols(
              CryptoGetSymbolsRequest request) {
            return getSymbols(request,null);
          }

          /**
           * Get list of available symbols
           */
          public CompletableFuture<TradewatchApiHttpResponse<CursorPageTCustomizedSymbolsOutFull>> getSymbols(
              CryptoGetSymbolsRequest request, RequestOptions requestOptions) {
            HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

              .addPathSegments("crypto/symbols");if (request.getSize().isPresent()) {
                QueryStringMapper.addQueryParameter(httpUrl, "size", request.getSize().get(), false);
              }
              if (request.getMode().isPresent()) {
                QueryStringMapper.addQueryParameter(httpUrl, "mode", request.getMode().get(), false);
              }
              if (request.getType().isPresent()) {
                QueryStringMapper.addQueryParameter(httpUrl, "type", request.getType().get(), false);
              }
              if (request.getCountry().isPresent()) {
                QueryStringMapper.addQueryParameter(httpUrl, "country", request.getCountry().get(), false);
              }
              if (request.getCursor().isPresent()) {
                QueryStringMapper.addQueryParameter(httpUrl, "cursor", request.getCursor().get(), false);
              }
              if (requestOptions != null) {
                requestOptions.getQueryParameters().forEach((_key, _value) -> {
                  httpUrl.addQueryParameter(_key, _value);
                } );
              }
              Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
              Request okhttpRequest = _requestBuilder.build();
              OkHttpClient client = clientOptions.httpClient();
              if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                client = clientOptions.httpClientWithTimeout(requestOptions);
              }
              CompletableFuture<TradewatchApiHttpResponse<CursorPageTCustomizedSymbolsOutFull>> future = new CompletableFuture<>();
              client.newCall(okhttpRequest).enqueue(new Callback() {
                @Override
                public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                  try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                      future.complete(new TradewatchApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, CursorPageTCustomizedSymbolsOutFull.class), response));
                      return;
                    }
                    try {
                      if (response.code() == 422) {
                        future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                        return;
                      }
                    }
                    catch (JsonProcessingException ignored) {
                      // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new TradewatchApiApiException("Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                  }
                  catch (IOException e) {
                    future.completeExceptionally(new TradewatchApiException("Network error executing HTTP request", e));
                  }
                }

                @Override
                public void onFailure(@NotNull Call call, @NotNull IOException e) {
                  future.completeExceptionally(new TradewatchApiException("Network error executing HTTP request", e));
                }
              });
              return future;
            }

            /**
             * Get recent crypto insights.
             */
            public CompletableFuture<TradewatchApiHttpResponse<CursorPageTCustomizedNewsOut>> getInsights(
                ) {
              return getInsights(CryptoGetInsightsRequest.builder().build());
            }

            /**
             * Get recent crypto insights.
             */
            public CompletableFuture<TradewatchApiHttpResponse<CursorPageTCustomizedNewsOut>> getInsights(
                RequestOptions requestOptions) {
              return getInsights(CryptoGetInsightsRequest.builder().build(),requestOptions);
            }

            /**
             * Get recent crypto insights.
             */
            public CompletableFuture<TradewatchApiHttpResponse<CursorPageTCustomizedNewsOut>> getInsights(
                CryptoGetInsightsRequest request) {
              return getInsights(request,null);
            }

            /**
             * Get recent crypto insights.
             */
            public CompletableFuture<TradewatchApiHttpResponse<CursorPageTCustomizedNewsOut>> getInsights(
                CryptoGetInsightsRequest request, RequestOptions requestOptions) {
              HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

                .addPathSegments("crypto/insights");if (request.getCursor().isPresent()) {
                  QueryStringMapper.addQueryParameter(httpUrl, "cursor", request.getCursor().get(), false);
                }
                if (request.getSize().isPresent()) {
                  QueryStringMapper.addQueryParameter(httpUrl, "size", request.getSize().get(), false);
                }
                if (requestOptions != null) {
                  requestOptions.getQueryParameters().forEach((_key, _value) -> {
                    httpUrl.addQueryParameter(_key, _value);
                  } );
                }
                Request.Builder _requestBuilder = new Request.Builder()
                  .url(httpUrl.build())
                  .method("GET", null)
                  .headers(Headers.of(clientOptions.headers(requestOptions)))
                  .addHeader("Accept", "application/json");
                Request okhttpRequest = _requestBuilder.build();
                OkHttpClient client = clientOptions.httpClient();
                if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                  client = clientOptions.httpClientWithTimeout(requestOptions);
                }
                CompletableFuture<TradewatchApiHttpResponse<CursorPageTCustomizedNewsOut>> future = new CompletableFuture<>();
                client.newCall(okhttpRequest).enqueue(new Callback() {
                  @Override
                  public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                    try (ResponseBody responseBody = response.body()) {
                      String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                      if (response.isSuccessful()) {
                        future.complete(new TradewatchApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, CursorPageTCustomizedNewsOut.class), response));
                        return;
                      }
                      try {
                        if (response.code() == 422) {
                          future.completeExceptionally(new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                          return;
                        }
                      }
                      catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                      }
                      Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                      future.completeExceptionally(new TradewatchApiApiException("Error with status code " + response.code(), response.code(), errorBody, response));
                      return;
                    }
                    catch (IOException e) {
                      future.completeExceptionally(new TradewatchApiException("Network error executing HTTP request", e));
                    }
                  }

                  @Override
                  public void onFailure(@NotNull Call call, @NotNull IOException e) {
                    future.completeExceptionally(new TradewatchApiException("Network error executing HTTP request", e));
                  }
                });
                return future;
              }
            }
