/**
 * This file was auto-generated by Fern from our API Definition.
 */

package io.tradewatch.client.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class AccountUsageStatisticsInterval {
  public static final AccountUsageStatisticsInterval VALUE1H = new AccountUsageStatisticsInterval(Value.VALUE1H, "1h");

  public static final AccountUsageStatisticsInterval VALUE1D = new AccountUsageStatisticsInterval(Value.VALUE1D, "1d");

  private final Value value;

  private final String string;

  AccountUsageStatisticsInterval(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof AccountUsageStatisticsInterval && this.string.equals(((AccountUsageStatisticsInterval) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case VALUE1H:
        return visitor.visitValue1H();
      case VALUE1D:
        return visitor.visitValue1D();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static AccountUsageStatisticsInterval valueOf(String value) {
    switch (value) {
      case "1h":
        return VALUE1H;
      case "1d":
        return VALUE1D;
      default:
        return new AccountUsageStatisticsInterval(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    VALUE1H,

    VALUE1D,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitValue1H();

    T visitValue1D();

    T visitUnknown(String unknownType);
  }
}
