/**
 * This file was auto-generated by Fern from our API Definition.
 */

package io.tradewatch.client.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.tradewatch.client.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ApiUsageDataTransfer.Builder.class
)
public final class ApiUsageDataTransfer {
  private final int request;

  private final int response;

  private final Map<String, Object> additionalProperties;

  private ApiUsageDataTransfer(int request, int response,
      Map<String, Object> additionalProperties) {
    this.request = request;
    this.response = response;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("request")
  public int getRequest() {
    return request;
  }

  @JsonProperty("response")
  public int getResponse() {
    return response;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ApiUsageDataTransfer && equalTo((ApiUsageDataTransfer) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ApiUsageDataTransfer other) {
    return request == other.request && response == other.response;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.request, this.response);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static RequestStage builder() {
    return new Builder();
  }

  public interface RequestStage {
    ResponseStage request(int request);

    Builder from(ApiUsageDataTransfer other);
  }

  public interface ResponseStage {
    _FinalStage response(int response);
  }

  public interface _FinalStage {
    ApiUsageDataTransfer build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements RequestStage, ResponseStage, _FinalStage {
    private int request;

    private int response;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(ApiUsageDataTransfer other) {
      request(other.getRequest());
      response(other.getResponse());
      return this;
    }

    @java.lang.Override
    @JsonSetter("request")
    public ResponseStage request(int request) {
      this.request = request;
      return this;
    }

    @java.lang.Override
    @JsonSetter("response")
    public _FinalStage response(int response) {
      this.response = response;
      return this;
    }

    @java.lang.Override
    public ApiUsageDataTransfer build() {
      return new ApiUsageDataTransfer(request, response, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
