/**
 * This file was auto-generated by Fern from our API Definition.
 */

package io.tradewatch.client.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.tradewatch.client.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CommodityTypesList.Builder.class
)
public final class CommodityTypesList {
  private final List<CommodityTypeObj> items;

  private final Map<String, Object> additionalProperties;

  private CommodityTypesList(List<CommodityTypeObj> items,
      Map<String, Object> additionalProperties) {
    this.items = items;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("items")
  public List<CommodityTypeObj> getItems() {
    return items;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CommodityTypesList && equalTo((CommodityTypesList) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CommodityTypesList other) {
    return items.equals(other.items);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.items);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private List<CommodityTypeObj> items = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(CommodityTypesList other) {
      items(other.getItems());
      return this;
    }

    @JsonSetter(
        value = "items",
        nulls = Nulls.SKIP
    )
    public Builder items(List<CommodityTypeObj> items) {
      this.items.clear();
      if (items != null) {
        this.items.addAll(items);
      }
      return this;
    }

    public Builder addItems(CommodityTypeObj items) {
      this.items.add(items);
      return this;
    }

    public Builder addAllItems(List<CommodityTypeObj> items) {
      if (items != null) {
        this.items.addAll(items);
      }
      return this;
    }

    public CommodityTypesList build() {
      return new CommodityTypesList(items, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
