/**
 * This file was auto-generated by Fern from our API Definition.
 */

package io.tradewatch.client.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.tradewatch.client.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CommodityTypeObj.Builder.class
)
public final class CommodityTypeObj {
  private final String symbol;

  private final Map<String, Object> additionalProperties;

  private CommodityTypeObj(String symbol, Map<String, Object> additionalProperties) {
    this.symbol = symbol;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Commodity type name
   */
  @JsonProperty("symbol")
  public String getSymbol() {
    return symbol;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CommodityTypeObj && equalTo((CommodityTypeObj) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CommodityTypeObj other) {
    return symbol.equals(other.symbol);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.symbol);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static SymbolStage builder() {
    return new Builder();
  }

  public interface SymbolStage {
    /**
     * <p>Commodity type name</p>
     */
    _FinalStage symbol(@NotNull String symbol);

    Builder from(CommodityTypeObj other);
  }

  public interface _FinalStage {
    CommodityTypeObj build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements SymbolStage, _FinalStage {
    private String symbol;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CommodityTypeObj other) {
      symbol(other.getSymbol());
      return this;
    }

    /**
     * <p>Commodity type name</p>
     * <p>Commodity type name</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("symbol")
    public _FinalStage symbol(@NotNull String symbol) {
      this.symbol = Objects.requireNonNull(symbol, "symbol must not be null");
      return this;
    }

    @java.lang.Override
    public CommodityTypeObj build() {
      return new CommodityTypeObj(symbol, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
