/**
 * This file was auto-generated by Fern from our API Definition.
 */

package io.tradewatch.client.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.tradewatch.client.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = Conversion.Builder.class
)
public final class Conversion {
  private final ConversionInfo info;

  private final ConversionQuery query;

  private final double result;

  private final Map<String, Object> additionalProperties;

  private Conversion(ConversionInfo info, ConversionQuery query, double result,
      Map<String, Object> additionalProperties) {
    this.info = info;
    this.query = query;
    this.result = result;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("info")
  public ConversionInfo getInfo() {
    return info;
  }

  @JsonProperty("query")
  public ConversionQuery getQuery() {
    return query;
  }

  @JsonProperty("result")
  public double getResult() {
    return result;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof Conversion && equalTo((Conversion) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(Conversion other) {
    return info.equals(other.info) && query.equals(other.query) && result == other.result;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.info, this.query, this.result);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static InfoStage builder() {
    return new Builder();
  }

  public interface InfoStage {
    QueryStage info(@NotNull ConversionInfo info);

    Builder from(Conversion other);
  }

  public interface QueryStage {
    ResultStage query(@NotNull ConversionQuery query);
  }

  public interface ResultStage {
    _FinalStage result(double result);
  }

  public interface _FinalStage {
    Conversion build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements InfoStage, QueryStage, ResultStage, _FinalStage {
    private ConversionInfo info;

    private ConversionQuery query;

    private double result;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(Conversion other) {
      info(other.getInfo());
      query(other.getQuery());
      result(other.getResult());
      return this;
    }

    @java.lang.Override
    @JsonSetter("info")
    public QueryStage info(@NotNull ConversionInfo info) {
      this.info = Objects.requireNonNull(info, "info must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("query")
    public ResultStage query(@NotNull ConversionQuery query) {
      this.query = Objects.requireNonNull(query, "query must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("result")
    public _FinalStage result(double result) {
      this.result = result;
      return this;
    }

    @java.lang.Override
    public Conversion build() {
      return new Conversion(info, query, result, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
