/**
 * This file was auto-generated by Fern from our API Definition.
 */

package io.tradewatch.client.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.tradewatch.client.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = ConversionInfo.Builder.class
)
public final class ConversionInfo {
  private final int timestamp;

  private final double rate;

  private final Map<String, Object> additionalProperties;

  private ConversionInfo(int timestamp, double rate, Map<String, Object> additionalProperties) {
    this.timestamp = timestamp;
    this.rate = rate;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("timestamp")
  public int getTimestamp() {
    return timestamp;
  }

  @JsonProperty("rate")
  public double getRate() {
    return rate;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof ConversionInfo && equalTo((ConversionInfo) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(ConversionInfo other) {
    return timestamp == other.timestamp && rate == other.rate;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.timestamp, this.rate);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static TimestampStage builder() {
    return new Builder();
  }

  public interface TimestampStage {
    RateStage timestamp(int timestamp);

    Builder from(ConversionInfo other);
  }

  public interface RateStage {
    _FinalStage rate(double rate);
  }

  public interface _FinalStage {
    ConversionInfo build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements TimestampStage, RateStage, _FinalStage {
    private int timestamp;

    private double rate;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(ConversionInfo other) {
      timestamp(other.getTimestamp());
      rate(other.getRate());
      return this;
    }

    @java.lang.Override
    @JsonSetter("timestamp")
    public RateStage timestamp(int timestamp) {
      this.timestamp = timestamp;
      return this;
    }

    @java.lang.Override
    @JsonSetter("rate")
    public _FinalStage rate(double rate) {
      this.rate = rate;
      return this;
    }

    @java.lang.Override
    public ConversionInfo build() {
      return new ConversionInfo(timestamp, rate, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
