/**
 * This file was auto-generated by Fern from our API Definition.
 */

package io.tradewatch.client.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.tradewatch.client.core.Nullable;
import io.tradewatch.client.core.NullableNonemptyFilter;
import io.tradewatch.client.core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CryptoExchangeItem.Builder.class
)
public final class CryptoExchangeItem {
  private final String id;

  private final String name;

  private final Optional<Integer> yearEstablished;

  private final Optional<String> country;

  private final String website;

  private final Map<String, Object> additionalProperties;

  private CryptoExchangeItem(String id, String name, Optional<Integer> yearEstablished,
      Optional<String> country, String website, Map<String, Object> additionalProperties) {
    this.id = id;
    this.name = name;
    this.yearEstablished = yearEstablished;
    this.country = country;
    this.website = website;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Exchange identifier (e.g. binance, coinbase-pro).
   */
  @JsonProperty("id")
  public String getId() {
    return id;
  }

  /**
   * @return Exchange name (e.g. Binance, Coinbase Pro).
   */
  @JsonProperty("name")
  public String getName() {
    return name;
  }

  /**
   * @return The year the exchange was established
   */
  @JsonIgnore
  public Optional<Integer> getYearEstablished() {
    if (yearEstablished == null) {
      return Optional.empty();
    }
    return yearEstablished;
  }

  /**
   * @return The country where the exchange is based.
   */
  @JsonIgnore
  public Optional<String> getCountry() {
    if (country == null) {
      return Optional.empty();
    }
    return country;
  }

  /**
   * @return The exchange's official website URL.
   */
  @JsonProperty("website")
  public String getWebsite() {
    return website;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("year_established")
  private Optional<Integer> _getYearEstablished() {
    return yearEstablished;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("country")
  private Optional<String> _getCountry() {
    return country;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CryptoExchangeItem && equalTo((CryptoExchangeItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CryptoExchangeItem other) {
    return id.equals(other.id) && name.equals(other.name) && yearEstablished.equals(other.yearEstablished) && country.equals(other.country) && website.equals(other.website);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.id, this.name, this.yearEstablished, this.country, this.website);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdStage builder() {
    return new Builder();
  }

  public interface IdStage {
    /**
     * <p>Exchange identifier (e.g. binance, coinbase-pro).</p>
     */
    NameStage id(@NotNull String id);

    Builder from(CryptoExchangeItem other);
  }

  public interface NameStage {
    /**
     * <p>Exchange name (e.g. Binance, Coinbase Pro).</p>
     */
    WebsiteStage name(@NotNull String name);
  }

  public interface WebsiteStage {
    /**
     * <p>The exchange's official website URL.</p>
     */
    _FinalStage website(@NotNull String website);
  }

  public interface _FinalStage {
    CryptoExchangeItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>The year the exchange was established</p>
     */
    _FinalStage yearEstablished(Optional<Integer> yearEstablished);

    _FinalStage yearEstablished(Integer yearEstablished);

    _FinalStage yearEstablished(Nullable<Integer> yearEstablished);

    /**
     * <p>The country where the exchange is based.</p>
     */
    _FinalStage country(Optional<String> country);

    _FinalStage country(String country);

    _FinalStage country(Nullable<String> country);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdStage, NameStage, WebsiteStage, _FinalStage {
    private String id;

    private String name;

    private String website;

    private Optional<String> country = Optional.empty();

    private Optional<Integer> yearEstablished = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(CryptoExchangeItem other) {
      id(other.getId());
      name(other.getName());
      yearEstablished(other.getYearEstablished());
      country(other.getCountry());
      website(other.getWebsite());
      return this;
    }

    /**
     * <p>Exchange identifier (e.g. binance, coinbase-pro).</p>
     * <p>Exchange identifier (e.g. binance, coinbase-pro).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("id")
    public NameStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    /**
     * <p>Exchange name (e.g. Binance, Coinbase Pro).</p>
     * <p>Exchange name (e.g. Binance, Coinbase Pro).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("name")
    public WebsiteStage name(@NotNull String name) {
      this.name = Objects.requireNonNull(name, "name must not be null");
      return this;
    }

    /**
     * <p>The exchange's official website URL.</p>
     * <p>The exchange's official website URL.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("website")
    public _FinalStage website(@NotNull String website) {
      this.website = Objects.requireNonNull(website, "website must not be null");
      return this;
    }

    /**
     * <p>The country where the exchange is based.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage country(Nullable<String> country) {
      if (country.isNull()) {
        this.country = null;
      }
      else if (country.isEmpty()) {
        this.country = Optional.empty();
      }
      else {
        this.country = Optional.of(country.get());
      }
      return this;
    }

    /**
     * <p>The country where the exchange is based.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage country(String country) {
      this.country = Optional.ofNullable(country);
      return this;
    }

    /**
     * <p>The country where the exchange is based.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "country",
        nulls = Nulls.SKIP
    )
    public _FinalStage country(Optional<String> country) {
      this.country = country;
      return this;
    }

    /**
     * <p>The year the exchange was established</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage yearEstablished(Nullable<Integer> yearEstablished) {
      if (yearEstablished.isNull()) {
        this.yearEstablished = null;
      }
      else if (yearEstablished.isEmpty()) {
        this.yearEstablished = Optional.empty();
      }
      else {
        this.yearEstablished = Optional.of(yearEstablished.get());
      }
      return this;
    }

    /**
     * <p>The year the exchange was established</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage yearEstablished(Integer yearEstablished) {
      this.yearEstablished = Optional.ofNullable(yearEstablished);
      return this;
    }

    /**
     * <p>The year the exchange was established</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "year_established",
        nulls = Nulls.SKIP
    )
    public _FinalStage yearEstablished(Optional<Integer> yearEstablished) {
      this.yearEstablished = yearEstablished;
      return this;
    }

    @java.lang.Override
    public CryptoExchangeItem build() {
      return new CryptoExchangeItem(id, name, yearEstablished, country, website, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
