/**
 * This file was auto-generated by Fern from our API Definition.
 */

package io.tradewatch.client.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.tradewatch.client.core.Nullable;
import io.tradewatch.client.core.NullableNonemptyFilter;
import io.tradewatch.client.core.ObjectMappers;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = CursorPageTCustomizedNewsOut.Builder.class
)
public final class CursorPageTCustomizedNewsOut {
  private final List<NewsOut> items;

  private final Optional<Integer> total;

  private final Optional<String> currentPage;

  private final Optional<String> currentPageBackwards;

  private final Optional<String> previousPage;

  private final Optional<String> nextPage;

  private final Map<String, Object> additionalProperties;

  private CursorPageTCustomizedNewsOut(List<NewsOut> items, Optional<Integer> total,
      Optional<String> currentPage, Optional<String> currentPageBackwards,
      Optional<String> previousPage, Optional<String> nextPage,
      Map<String, Object> additionalProperties) {
    this.items = items;
    this.total = total;
    this.currentPage = currentPage;
    this.currentPageBackwards = currentPageBackwards;
    this.previousPage = previousPage;
    this.nextPage = nextPage;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("items")
  public List<NewsOut> getItems() {
    return items;
  }

  /**
   * @return Total items
   */
  @JsonIgnore
  public Optional<Integer> getTotal() {
    if (total == null) {
      return Optional.empty();
    }
    return total;
  }

  /**
   * @return Cursor to refetch the current page
   */
  @JsonIgnore
  public Optional<String> getCurrentPage() {
    if (currentPage == null) {
      return Optional.empty();
    }
    return currentPage;
  }

  /**
   * @return Cursor to refetch the current page starting from the last item
   */
  @JsonIgnore
  public Optional<String> getCurrentPageBackwards() {
    if (currentPageBackwards == null) {
      return Optional.empty();
    }
    return currentPageBackwards;
  }

  /**
   * @return Cursor for the previous page
   */
  @JsonIgnore
  public Optional<String> getPreviousPage() {
    if (previousPage == null) {
      return Optional.empty();
    }
    return previousPage;
  }

  /**
   * @return Cursor for the next page
   */
  @JsonIgnore
  public Optional<String> getNextPage() {
    if (nextPage == null) {
      return Optional.empty();
    }
    return nextPage;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("total")
  private Optional<Integer> _getTotal() {
    return total;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("current_page")
  private Optional<String> _getCurrentPage() {
    return currentPage;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("current_page_backwards")
  private Optional<String> _getCurrentPageBackwards() {
    return currentPageBackwards;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("previous_page")
  private Optional<String> _getPreviousPage() {
    return previousPage;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("next_page")
  private Optional<String> _getNextPage() {
    return nextPage;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof CursorPageTCustomizedNewsOut && equalTo((CursorPageTCustomizedNewsOut) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(CursorPageTCustomizedNewsOut other) {
    return items.equals(other.items) && total.equals(other.total) && currentPage.equals(other.currentPage) && currentPageBackwards.equals(other.currentPageBackwards) && previousPage.equals(other.previousPage) && nextPage.equals(other.nextPage);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.items, this.total, this.currentPage, this.currentPageBackwards, this.previousPage, this.nextPage);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private List<NewsOut> items = new ArrayList<>();

    private Optional<Integer> total = Optional.empty();

    private Optional<String> currentPage = Optional.empty();

    private Optional<String> currentPageBackwards = Optional.empty();

    private Optional<String> previousPage = Optional.empty();

    private Optional<String> nextPage = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(CursorPageTCustomizedNewsOut other) {
      items(other.getItems());
      total(other.getTotal());
      currentPage(other.getCurrentPage());
      currentPageBackwards(other.getCurrentPageBackwards());
      previousPage(other.getPreviousPage());
      nextPage(other.getNextPage());
      return this;
    }

    @JsonSetter(
        value = "items",
        nulls = Nulls.SKIP
    )
    public Builder items(List<NewsOut> items) {
      this.items.clear();
      if (items != null) {
        this.items.addAll(items);
      }
      return this;
    }

    public Builder addItems(NewsOut items) {
      this.items.add(items);
      return this;
    }

    public Builder addAllItems(List<NewsOut> items) {
      if (items != null) {
        this.items.addAll(items);
      }
      return this;
    }

    /**
     * <p>Total items</p>
     */
    @JsonSetter(
        value = "total",
        nulls = Nulls.SKIP
    )
    public Builder total(Optional<Integer> total) {
      this.total = total;
      return this;
    }

    public Builder total(Integer total) {
      this.total = Optional.ofNullable(total);
      return this;
    }

    public Builder total(Nullable<Integer> total) {
      if (total.isNull()) {
        this.total = null;
      }
      else if (total.isEmpty()) {
        this.total = Optional.empty();
      }
      else {
        this.total = Optional.of(total.get());
      }
      return this;
    }

    /**
     * <p>Cursor to refetch the current page</p>
     */
    @JsonSetter(
        value = "current_page",
        nulls = Nulls.SKIP
    )
    public Builder currentPage(Optional<String> currentPage) {
      this.currentPage = currentPage;
      return this;
    }

    public Builder currentPage(String currentPage) {
      this.currentPage = Optional.ofNullable(currentPage);
      return this;
    }

    public Builder currentPage(Nullable<String> currentPage) {
      if (currentPage.isNull()) {
        this.currentPage = null;
      }
      else if (currentPage.isEmpty()) {
        this.currentPage = Optional.empty();
      }
      else {
        this.currentPage = Optional.of(currentPage.get());
      }
      return this;
    }

    /**
     * <p>Cursor to refetch the current page starting from the last item</p>
     */
    @JsonSetter(
        value = "current_page_backwards",
        nulls = Nulls.SKIP
    )
    public Builder currentPageBackwards(Optional<String> currentPageBackwards) {
      this.currentPageBackwards = currentPageBackwards;
      return this;
    }

    public Builder currentPageBackwards(String currentPageBackwards) {
      this.currentPageBackwards = Optional.ofNullable(currentPageBackwards);
      return this;
    }

    public Builder currentPageBackwards(Nullable<String> currentPageBackwards) {
      if (currentPageBackwards.isNull()) {
        this.currentPageBackwards = null;
      }
      else if (currentPageBackwards.isEmpty()) {
        this.currentPageBackwards = Optional.empty();
      }
      else {
        this.currentPageBackwards = Optional.of(currentPageBackwards.get());
      }
      return this;
    }

    /**
     * <p>Cursor for the previous page</p>
     */
    @JsonSetter(
        value = "previous_page",
        nulls = Nulls.SKIP
    )
    public Builder previousPage(Optional<String> previousPage) {
      this.previousPage = previousPage;
      return this;
    }

    public Builder previousPage(String previousPage) {
      this.previousPage = Optional.ofNullable(previousPage);
      return this;
    }

    public Builder previousPage(Nullable<String> previousPage) {
      if (previousPage.isNull()) {
        this.previousPage = null;
      }
      else if (previousPage.isEmpty()) {
        this.previousPage = Optional.empty();
      }
      else {
        this.previousPage = Optional.of(previousPage.get());
      }
      return this;
    }

    /**
     * <p>Cursor for the next page</p>
     */
    @JsonSetter(
        value = "next_page",
        nulls = Nulls.SKIP
    )
    public Builder nextPage(Optional<String> nextPage) {
      this.nextPage = nextPage;
      return this;
    }

    public Builder nextPage(String nextPage) {
      this.nextPage = Optional.ofNullable(nextPage);
      return this;
    }

    public Builder nextPage(Nullable<String> nextPage) {
      if (nextPage.isNull()) {
        this.nextPage = null;
      }
      else if (nextPage.isEmpty()) {
        this.nextPage = Optional.empty();
      }
      else {
        this.nextPage = Optional.of(nextPage.get());
      }
      return this;
    }

    public CursorPageTCustomizedNewsOut build() {
      return new CursorPageTCustomizedNewsOut(items, total, currentPage, currentPageBackwards, previousPage, nextPage, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
