/**
 * This file was auto-generated by Fern from our API Definition.
 */

package io.tradewatch.client.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.tradewatch.client.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = HistoricalRawTick.Builder.class
)
public final class HistoricalRawTick {
  private final OffsetDateTime time;

  private final double ask;

  private final double bid;

  private final double mid;

  private final Map<String, Object> additionalProperties;

  private HistoricalRawTick(OffsetDateTime time, double ask, double bid, double mid,
      Map<String, Object> additionalProperties) {
    this.time = time;
    this.ask = ask;
    this.bid = bid;
    this.mid = mid;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("time")
  public OffsetDateTime getTime() {
    return time;
  }

  @JsonProperty("ask")
  public double getAsk() {
    return ask;
  }

  @JsonProperty("bid")
  public double getBid() {
    return bid;
  }

  @JsonProperty("mid")
  public double getMid() {
    return mid;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof HistoricalRawTick && equalTo((HistoricalRawTick) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(HistoricalRawTick other) {
    return time.equals(other.time) && ask == other.ask && bid == other.bid && mid == other.mid;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.time, this.ask, this.bid, this.mid);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static TimeStage builder() {
    return new Builder();
  }

  public interface TimeStage {
    AskStage time(@NotNull OffsetDateTime time);

    Builder from(HistoricalRawTick other);
  }

  public interface AskStage {
    BidStage ask(double ask);
  }

  public interface BidStage {
    MidStage bid(double bid);
  }

  public interface MidStage {
    _FinalStage mid(double mid);
  }

  public interface _FinalStage {
    HistoricalRawTick build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements TimeStage, AskStage, BidStage, MidStage, _FinalStage {
    private OffsetDateTime time;

    private double ask;

    private double bid;

    private double mid;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(HistoricalRawTick other) {
      time(other.getTime());
      ask(other.getAsk());
      bid(other.getBid());
      mid(other.getMid());
      return this;
    }

    @java.lang.Override
    @JsonSetter("time")
    public AskStage time(@NotNull OffsetDateTime time) {
      this.time = Objects.requireNonNull(time, "time must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("ask")
    public BidStage ask(double ask) {
      this.ask = ask;
      return this;
    }

    @java.lang.Override
    @JsonSetter("bid")
    public MidStage bid(double bid) {
      this.bid = bid;
      return this;
    }

    @java.lang.Override
    @JsonSetter("mid")
    public _FinalStage mid(double mid) {
      this.mid = mid;
      return this;
    }

    @java.lang.Override
    public HistoricalRawTick build() {
      return new HistoricalRawTick(time, ask, bid, mid, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
