/**
 * This file was auto-generated by Fern from our API Definition.
 */

package io.tradewatch.client.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.tradewatch.client.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = HistoricalOhlcResponse.Builder.class
)
public final class HistoricalOhlcResponse {
  private final String symbol;

  private final String resolution;

  private final List<HistoricalOhlcCandle> items;

  private final Map<String, Object> additionalProperties;

  private HistoricalOhlcResponse(String symbol, String resolution, List<HistoricalOhlcCandle> items,
      Map<String, Object> additionalProperties) {
    this.symbol = symbol;
    this.resolution = resolution;
    this.items = items;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("symbol")
  public String getSymbol() {
    return symbol;
  }

  @JsonProperty("resolution")
  public String getResolution() {
    return resolution;
  }

  @JsonProperty("items")
  public List<HistoricalOhlcCandle> getItems() {
    return items;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof HistoricalOhlcResponse && equalTo((HistoricalOhlcResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(HistoricalOhlcResponse other) {
    return symbol.equals(other.symbol) && resolution.equals(other.resolution) && items.equals(other.items);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.symbol, this.resolution, this.items);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static SymbolStage builder() {
    return new Builder();
  }

  public interface SymbolStage {
    ResolutionStage symbol(@NotNull String symbol);

    Builder from(HistoricalOhlcResponse other);
  }

  public interface ResolutionStage {
    _FinalStage resolution(@NotNull String resolution);
  }

  public interface _FinalStage {
    HistoricalOhlcResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage items(List<HistoricalOhlcCandle> items);

    _FinalStage addItems(HistoricalOhlcCandle items);

    _FinalStage addAllItems(List<HistoricalOhlcCandle> items);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements SymbolStage, ResolutionStage, _FinalStage {
    private String symbol;

    private String resolution;

    private List<HistoricalOhlcCandle> items = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(HistoricalOhlcResponse other) {
      symbol(other.getSymbol());
      resolution(other.getResolution());
      items(other.getItems());
      return this;
    }

    @java.lang.Override
    @JsonSetter("symbol")
    public ResolutionStage symbol(@NotNull String symbol) {
      this.symbol = Objects.requireNonNull(symbol, "symbol must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("resolution")
    public _FinalStage resolution(@NotNull String resolution) {
      this.resolution = Objects.requireNonNull(resolution, "resolution must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllItems(List<HistoricalOhlcCandle> items) {
      if (items != null) {
        this.items.addAll(items);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addItems(HistoricalOhlcCandle items) {
      this.items.add(items);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "items",
        nulls = Nulls.SKIP
    )
    public _FinalStage items(List<HistoricalOhlcCandle> items) {
      this.items.clear();
      if (items != null) {
        this.items.addAll(items);
      }
      return this;
    }

    @java.lang.Override
    public HistoricalOhlcResponse build() {
      return new HistoricalOhlcResponse(symbol, resolution, items, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
