/**
 * This file was auto-generated by Fern from our API Definition.
 */

package io.tradewatch.client.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.tradewatch.client.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = LastQuote.Builder.class
)
public final class LastQuote {
  private final String symbol;

  private final double ask;

  private final double bid;

  private final double mid;

  private final int timestamp;

  private final Map<String, Object> additionalProperties;

  private LastQuote(String symbol, double ask, double bid, double mid, int timestamp,
      Map<String, Object> additionalProperties) {
    this.symbol = symbol;
    this.ask = ask;
    this.bid = bid;
    this.mid = mid;
    this.timestamp = timestamp;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Symbol name
   */
  @JsonProperty("symbol")
  public String getSymbol() {
    return symbol;
  }

  /**
   * @return The ask price.
   */
  @JsonProperty("ask")
  public double getAsk() {
    return ask;
  }

  /**
   * @return The bid price.
   */
  @JsonProperty("bid")
  public double getBid() {
    return bid;
  }

  /**
   * @return The mid price.
   */
  @JsonProperty("mid")
  public double getMid() {
    return mid;
  }

  @JsonProperty("timestamp")
  public int getTimestamp() {
    return timestamp;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof LastQuote && equalTo((LastQuote) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(LastQuote other) {
    return symbol.equals(other.symbol) && ask == other.ask && bid == other.bid && mid == other.mid && timestamp == other.timestamp;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.symbol, this.ask, this.bid, this.mid, this.timestamp);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static SymbolStage builder() {
    return new Builder();
  }

  public interface SymbolStage {
    /**
     * <p>Symbol name</p>
     */
    AskStage symbol(@NotNull String symbol);

    Builder from(LastQuote other);
  }

  public interface AskStage {
    /**
     * <p>The ask price.</p>
     */
    BidStage ask(double ask);
  }

  public interface BidStage {
    /**
     * <p>The bid price.</p>
     */
    MidStage bid(double bid);
  }

  public interface MidStage {
    /**
     * <p>The mid price.</p>
     */
    TimestampStage mid(double mid);
  }

  public interface TimestampStage {
    _FinalStage timestamp(int timestamp);
  }

  public interface _FinalStage {
    LastQuote build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements SymbolStage, AskStage, BidStage, MidStage, TimestampStage, _FinalStage {
    private String symbol;

    private double ask;

    private double bid;

    private double mid;

    private int timestamp;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(LastQuote other) {
      symbol(other.getSymbol());
      ask(other.getAsk());
      bid(other.getBid());
      mid(other.getMid());
      timestamp(other.getTimestamp());
      return this;
    }

    /**
     * <p>Symbol name</p>
     * <p>Symbol name</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("symbol")
    public AskStage symbol(@NotNull String symbol) {
      this.symbol = Objects.requireNonNull(symbol, "symbol must not be null");
      return this;
    }

    /**
     * <p>The ask price.</p>
     * <p>The ask price.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("ask")
    public BidStage ask(double ask) {
      this.ask = ask;
      return this;
    }

    /**
     * <p>The bid price.</p>
     * <p>The bid price.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("bid")
    public MidStage bid(double bid) {
      this.bid = bid;
      return this;
    }

    /**
     * <p>The mid price.</p>
     * <p>The mid price.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("mid")
    public TimestampStage mid(double mid) {
      this.mid = mid;
      return this;
    }

    @java.lang.Override
    @JsonSetter("timestamp")
    public _FinalStage timestamp(int timestamp) {
      this.timestamp = timestamp;
      return this;
    }

    @java.lang.Override
    public LastQuote build() {
      return new LastQuote(symbol, ask, bid, mid, timestamp, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
