/**
 * This file was auto-generated by Fern from our API Definition.
 */

package io.tradewatch.client.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.tradewatch.client.core.Nullable;
import io.tradewatch.client.core.NullableNonemptyFilter;
import io.tradewatch.client.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = MarketResponse.Builder.class
)
public final class MarketResponse {
  private final String mic;

  private final String exchange;

  private final Optional<String> acronym;

  private final String lei;

  private final String url;

  private final String city;

  private final String country;

  private final String countryCode;

  private final String flag;

  private final String currencyName;

  private final String currencyCode;

  private final String currencySymbol;

  private final String region;

  private final String timezone;

  private final String timezoneAbbr;

  private final String utcOffset;

  private final boolean dst;

  private final Optional<String> previousDstTransition;

  private final Optional<String> nextDstTransition;

  private final List<Weekday> workingDays;

  private final String openTime;

  private final String closeTime;

  private final Optional<String> earlyCloseTime;

  private final Map<String, Object> additionalProperties;

  private MarketResponse(String mic, String exchange, Optional<String> acronym, String lei,
      String url, String city, String country, String countryCode, String flag, String currencyName,
      String currencyCode, String currencySymbol, String region, String timezone,
      String timezoneAbbr, String utcOffset, boolean dst, Optional<String> previousDstTransition,
      Optional<String> nextDstTransition, List<Weekday> workingDays, String openTime,
      String closeTime, Optional<String> earlyCloseTime, Map<String, Object> additionalProperties) {
    this.mic = mic;
    this.exchange = exchange;
    this.acronym = acronym;
    this.lei = lei;
    this.url = url;
    this.city = city;
    this.country = country;
    this.countryCode = countryCode;
    this.flag = flag;
    this.currencyName = currencyName;
    this.currencyCode = currencyCode;
    this.currencySymbol = currencySymbol;
    this.region = region;
    this.timezone = timezone;
    this.timezoneAbbr = timezoneAbbr;
    this.utcOffset = utcOffset;
    this.dst = dst;
    this.previousDstTransition = previousDstTransition;
    this.nextDstTransition = nextDstTransition;
    this.workingDays = workingDays;
    this.openTime = openTime;
    this.closeTime = closeTime;
    this.earlyCloseTime = earlyCloseTime;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Market Identifier Code (ISO 10383)
   */
  @JsonProperty("mic")
  public String getMic() {
    return mic;
  }

  /**
   * @return Full name of the exchange
   */
  @JsonProperty("exchange")
  public String getExchange() {
    return exchange;
  }

  /**
   * @return Exchange acronym
   */
  @JsonIgnore
  public Optional<String> getAcronym() {
    if (acronym == null) {
      return Optional.empty();
    }
    return acronym;
  }

  /**
   * @return Legal Entity Identifier
   */
  @JsonProperty("lei")
  public String getLei() {
    return lei;
  }

  /**
   * @return Exchange website URL
   */
  @JsonProperty("url")
  public String getUrl() {
    return url;
  }

  /**
   * @return City where the exchange is located
   */
  @JsonProperty("city")
  public String getCity() {
    return city;
  }

  /**
   * @return Country where the exchange is located
   */
  @JsonProperty("country")
  public String getCountry() {
    return country;
  }

  /**
   * @return ISO 3166-1 alpha-2 country code
   */
  @JsonProperty("country_code")
  public String getCountryCode() {
    return countryCode;
  }

  /**
   * @return Country flag emoji
   */
  @JsonProperty("flag")
  public String getFlag() {
    return flag;
  }

  /**
   * @return Name of the primary currency used
   */
  @JsonProperty("currency_name")
  public String getCurrencyName() {
    return currencyName;
  }

  /**
   * @return ISO 4217 currency code
   */
  @JsonProperty("currency_code")
  public String getCurrencyCode() {
    return currencyCode;
  }

  /**
   * @return Symbol of the currency
   */
  @JsonProperty("currency_symbol")
  public String getCurrencySymbol() {
    return currencySymbol;
  }

  /**
   * @return Geographical region
   */
  @JsonProperty("region")
  public String getRegion() {
    return region;
  }

  /**
   * @return Timezone identifier (IANA database)
   */
  @JsonProperty("timezone")
  public String getTimezone() {
    return timezone;
  }

  /**
   * @return Timezone abbreviation
   */
  @JsonProperty("timezone_abbr")
  public String getTimezoneAbbr() {
    return timezoneAbbr;
  }

  /**
   * @return UTC offset in hours
   */
  @JsonProperty("utc_offset")
  public String getUtcOffset() {
    return utcOffset;
  }

  /**
   * @return Whether Daylight Saving Time is currently observed
   */
  @JsonProperty("dst")
  public boolean getDst() {
    return dst;
  }

  /**
   * @return Date of the previous DST transition
   */
  @JsonIgnore
  public Optional<String> getPreviousDstTransition() {
    if (previousDstTransition == null) {
      return Optional.empty();
    }
    return previousDstTransition;
  }

  /**
   * @return Date of the next DST transition
   */
  @JsonIgnore
  public Optional<String> getNextDstTransition() {
    if (nextDstTransition == null) {
      return Optional.empty();
    }
    return nextDstTransition;
  }

  /**
   * @return List of working days
   */
  @JsonProperty("working_days")
  public List<Weekday> getWorkingDays() {
    return workingDays;
  }

  /**
   * @return Regular trading session opening time
   */
  @JsonProperty("open_time")
  public String getOpenTime() {
    return openTime;
  }

  /**
   * @return Regular trading session closing time
   */
  @JsonProperty("close_time")
  public String getCloseTime() {
    return closeTime;
  }

  /**
   * @return Trading session closing time on early close days
   */
  @JsonIgnore
  public Optional<String> getEarlyCloseTime() {
    if (earlyCloseTime == null) {
      return Optional.empty();
    }
    return earlyCloseTime;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("acronym")
  private Optional<String> _getAcronym() {
    return acronym;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("previous_dst_transition")
  private Optional<String> _getPreviousDstTransition() {
    return previousDstTransition;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("next_dst_transition")
  private Optional<String> _getNextDstTransition() {
    return nextDstTransition;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("early_close_time")
  private Optional<String> _getEarlyCloseTime() {
    return earlyCloseTime;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof MarketResponse && equalTo((MarketResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(MarketResponse other) {
    return mic.equals(other.mic) && exchange.equals(other.exchange) && acronym.equals(other.acronym) && lei.equals(other.lei) && url.equals(other.url) && city.equals(other.city) && country.equals(other.country) && countryCode.equals(other.countryCode) && flag.equals(other.flag) && currencyName.equals(other.currencyName) && currencyCode.equals(other.currencyCode) && currencySymbol.equals(other.currencySymbol) && region.equals(other.region) && timezone.equals(other.timezone) && timezoneAbbr.equals(other.timezoneAbbr) && utcOffset.equals(other.utcOffset) && dst == other.dst && previousDstTransition.equals(other.previousDstTransition) && nextDstTransition.equals(other.nextDstTransition) && workingDays.equals(other.workingDays) && openTime.equals(other.openTime) && closeTime.equals(other.closeTime) && earlyCloseTime.equals(other.earlyCloseTime);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.mic, this.exchange, this.acronym, this.lei, this.url, this.city, this.country, this.countryCode, this.flag, this.currencyName, this.currencyCode, this.currencySymbol, this.region, this.timezone, this.timezoneAbbr, this.utcOffset, this.dst, this.previousDstTransition, this.nextDstTransition, this.workingDays, this.openTime, this.closeTime, this.earlyCloseTime);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static MicStage builder() {
    return new Builder();
  }

  public interface MicStage {
    /**
     * <p>Market Identifier Code (ISO 10383)</p>
     */
    ExchangeStage mic(@NotNull String mic);

    Builder from(MarketResponse other);
  }

  public interface ExchangeStage {
    /**
     * <p>Full name of the exchange</p>
     */
    LeiStage exchange(@NotNull String exchange);
  }

  public interface LeiStage {
    /**
     * <p>Legal Entity Identifier</p>
     */
    UrlStage lei(@NotNull String lei);
  }

  public interface UrlStage {
    /**
     * <p>Exchange website URL</p>
     */
    CityStage url(@NotNull String url);
  }

  public interface CityStage {
    /**
     * <p>City where the exchange is located</p>
     */
    CountryStage city(@NotNull String city);
  }

  public interface CountryStage {
    /**
     * <p>Country where the exchange is located</p>
     */
    CountryCodeStage country(@NotNull String country);
  }

  public interface CountryCodeStage {
    /**
     * <p>ISO 3166-1 alpha-2 country code</p>
     */
    FlagStage countryCode(@NotNull String countryCode);
  }

  public interface FlagStage {
    /**
     * <p>Country flag emoji</p>
     */
    CurrencyNameStage flag(@NotNull String flag);
  }

  public interface CurrencyNameStage {
    /**
     * <p>Name of the primary currency used</p>
     */
    CurrencyCodeStage currencyName(@NotNull String currencyName);
  }

  public interface CurrencyCodeStage {
    /**
     * <p>ISO 4217 currency code</p>
     */
    CurrencySymbolStage currencyCode(@NotNull String currencyCode);
  }

  public interface CurrencySymbolStage {
    /**
     * <p>Symbol of the currency</p>
     */
    RegionStage currencySymbol(@NotNull String currencySymbol);
  }

  public interface RegionStage {
    /**
     * <p>Geographical region</p>
     */
    TimezoneStage region(@NotNull String region);
  }

  public interface TimezoneStage {
    /**
     * <p>Timezone identifier (IANA database)</p>
     */
    TimezoneAbbrStage timezone(@NotNull String timezone);
  }

  public interface TimezoneAbbrStage {
    /**
     * <p>Timezone abbreviation</p>
     */
    UtcOffsetStage timezoneAbbr(@NotNull String timezoneAbbr);
  }

  public interface UtcOffsetStage {
    /**
     * <p>UTC offset in hours</p>
     */
    DstStage utcOffset(@NotNull String utcOffset);
  }

  public interface DstStage {
    /**
     * <p>Whether Daylight Saving Time is currently observed</p>
     */
    OpenTimeStage dst(boolean dst);
  }

  public interface OpenTimeStage {
    /**
     * <p>Regular trading session opening time</p>
     */
    CloseTimeStage openTime(@NotNull String openTime);
  }

  public interface CloseTimeStage {
    /**
     * <p>Regular trading session closing time</p>
     */
    _FinalStage closeTime(@NotNull String closeTime);
  }

  public interface _FinalStage {
    MarketResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Exchange acronym</p>
     */
    _FinalStage acronym(Optional<String> acronym);

    _FinalStage acronym(String acronym);

    _FinalStage acronym(Nullable<String> acronym);

    /**
     * <p>Date of the previous DST transition</p>
     */
    _FinalStage previousDstTransition(Optional<String> previousDstTransition);

    _FinalStage previousDstTransition(String previousDstTransition);

    _FinalStage previousDstTransition(Nullable<String> previousDstTransition);

    /**
     * <p>Date of the next DST transition</p>
     */
    _FinalStage nextDstTransition(Optional<String> nextDstTransition);

    _FinalStage nextDstTransition(String nextDstTransition);

    _FinalStage nextDstTransition(Nullable<String> nextDstTransition);

    /**
     * <p>List of working days</p>
     */
    _FinalStage workingDays(List<Weekday> workingDays);

    _FinalStage addWorkingDays(Weekday workingDays);

    _FinalStage addAllWorkingDays(List<Weekday> workingDays);

    /**
     * <p>Trading session closing time on early close days</p>
     */
    _FinalStage earlyCloseTime(Optional<String> earlyCloseTime);

    _FinalStage earlyCloseTime(String earlyCloseTime);

    _FinalStage earlyCloseTime(Nullable<String> earlyCloseTime);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements MicStage, ExchangeStage, LeiStage, UrlStage, CityStage, CountryStage, CountryCodeStage, FlagStage, CurrencyNameStage, CurrencyCodeStage, CurrencySymbolStage, RegionStage, TimezoneStage, TimezoneAbbrStage, UtcOffsetStage, DstStage, OpenTimeStage, CloseTimeStage, _FinalStage {
    private String mic;

    private String exchange;

    private String lei;

    private String url;

    private String city;

    private String country;

    private String countryCode;

    private String flag;

    private String currencyName;

    private String currencyCode;

    private String currencySymbol;

    private String region;

    private String timezone;

    private String timezoneAbbr;

    private String utcOffset;

    private boolean dst;

    private String openTime;

    private String closeTime;

    private Optional<String> earlyCloseTime = Optional.empty();

    private List<Weekday> workingDays = new ArrayList<>();

    private Optional<String> nextDstTransition = Optional.empty();

    private Optional<String> previousDstTransition = Optional.empty();

    private Optional<String> acronym = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(MarketResponse other) {
      mic(other.getMic());
      exchange(other.getExchange());
      acronym(other.getAcronym());
      lei(other.getLei());
      url(other.getUrl());
      city(other.getCity());
      country(other.getCountry());
      countryCode(other.getCountryCode());
      flag(other.getFlag());
      currencyName(other.getCurrencyName());
      currencyCode(other.getCurrencyCode());
      currencySymbol(other.getCurrencySymbol());
      region(other.getRegion());
      timezone(other.getTimezone());
      timezoneAbbr(other.getTimezoneAbbr());
      utcOffset(other.getUtcOffset());
      dst(other.getDst());
      previousDstTransition(other.getPreviousDstTransition());
      nextDstTransition(other.getNextDstTransition());
      workingDays(other.getWorkingDays());
      openTime(other.getOpenTime());
      closeTime(other.getCloseTime());
      earlyCloseTime(other.getEarlyCloseTime());
      return this;
    }

    /**
     * <p>Market Identifier Code (ISO 10383)</p>
     * <p>Market Identifier Code (ISO 10383)</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("mic")
    public ExchangeStage mic(@NotNull String mic) {
      this.mic = Objects.requireNonNull(mic, "mic must not be null");
      return this;
    }

    /**
     * <p>Full name of the exchange</p>
     * <p>Full name of the exchange</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("exchange")
    public LeiStage exchange(@NotNull String exchange) {
      this.exchange = Objects.requireNonNull(exchange, "exchange must not be null");
      return this;
    }

    /**
     * <p>Legal Entity Identifier</p>
     * <p>Legal Entity Identifier</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("lei")
    public UrlStage lei(@NotNull String lei) {
      this.lei = Objects.requireNonNull(lei, "lei must not be null");
      return this;
    }

    /**
     * <p>Exchange website URL</p>
     * <p>Exchange website URL</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("url")
    public CityStage url(@NotNull String url) {
      this.url = Objects.requireNonNull(url, "url must not be null");
      return this;
    }

    /**
     * <p>City where the exchange is located</p>
     * <p>City where the exchange is located</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("city")
    public CountryStage city(@NotNull String city) {
      this.city = Objects.requireNonNull(city, "city must not be null");
      return this;
    }

    /**
     * <p>Country where the exchange is located</p>
     * <p>Country where the exchange is located</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("country")
    public CountryCodeStage country(@NotNull String country) {
      this.country = Objects.requireNonNull(country, "country must not be null");
      return this;
    }

    /**
     * <p>ISO 3166-1 alpha-2 country code</p>
     * <p>ISO 3166-1 alpha-2 country code</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("country_code")
    public FlagStage countryCode(@NotNull String countryCode) {
      this.countryCode = Objects.requireNonNull(countryCode, "countryCode must not be null");
      return this;
    }

    /**
     * <p>Country flag emoji</p>
     * <p>Country flag emoji</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("flag")
    public CurrencyNameStage flag(@NotNull String flag) {
      this.flag = Objects.requireNonNull(flag, "flag must not be null");
      return this;
    }

    /**
     * <p>Name of the primary currency used</p>
     * <p>Name of the primary currency used</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("currency_name")
    public CurrencyCodeStage currencyName(@NotNull String currencyName) {
      this.currencyName = Objects.requireNonNull(currencyName, "currencyName must not be null");
      return this;
    }

    /**
     * <p>ISO 4217 currency code</p>
     * <p>ISO 4217 currency code</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("currency_code")
    public CurrencySymbolStage currencyCode(@NotNull String currencyCode) {
      this.currencyCode = Objects.requireNonNull(currencyCode, "currencyCode must not be null");
      return this;
    }

    /**
     * <p>Symbol of the currency</p>
     * <p>Symbol of the currency</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("currency_symbol")
    public RegionStage currencySymbol(@NotNull String currencySymbol) {
      this.currencySymbol = Objects.requireNonNull(currencySymbol, "currencySymbol must not be null");
      return this;
    }

    /**
     * <p>Geographical region</p>
     * <p>Geographical region</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("region")
    public TimezoneStage region(@NotNull String region) {
      this.region = Objects.requireNonNull(region, "region must not be null");
      return this;
    }

    /**
     * <p>Timezone identifier (IANA database)</p>
     * <p>Timezone identifier (IANA database)</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("timezone")
    public TimezoneAbbrStage timezone(@NotNull String timezone) {
      this.timezone = Objects.requireNonNull(timezone, "timezone must not be null");
      return this;
    }

    /**
     * <p>Timezone abbreviation</p>
     * <p>Timezone abbreviation</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("timezone_abbr")
    public UtcOffsetStage timezoneAbbr(@NotNull String timezoneAbbr) {
      this.timezoneAbbr = Objects.requireNonNull(timezoneAbbr, "timezoneAbbr must not be null");
      return this;
    }

    /**
     * <p>UTC offset in hours</p>
     * <p>UTC offset in hours</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("utc_offset")
    public DstStage utcOffset(@NotNull String utcOffset) {
      this.utcOffset = Objects.requireNonNull(utcOffset, "utcOffset must not be null");
      return this;
    }

    /**
     * <p>Whether Daylight Saving Time is currently observed</p>
     * <p>Whether Daylight Saving Time is currently observed</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("dst")
    public OpenTimeStage dst(boolean dst) {
      this.dst = dst;
      return this;
    }

    /**
     * <p>Regular trading session opening time</p>
     * <p>Regular trading session opening time</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("open_time")
    public CloseTimeStage openTime(@NotNull String openTime) {
      this.openTime = Objects.requireNonNull(openTime, "openTime must not be null");
      return this;
    }

    /**
     * <p>Regular trading session closing time</p>
     * <p>Regular trading session closing time</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("close_time")
    public _FinalStage closeTime(@NotNull String closeTime) {
      this.closeTime = Objects.requireNonNull(closeTime, "closeTime must not be null");
      return this;
    }

    /**
     * <p>Trading session closing time on early close days</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage earlyCloseTime(Nullable<String> earlyCloseTime) {
      if (earlyCloseTime.isNull()) {
        this.earlyCloseTime = null;
      }
      else if (earlyCloseTime.isEmpty()) {
        this.earlyCloseTime = Optional.empty();
      }
      else {
        this.earlyCloseTime = Optional.of(earlyCloseTime.get());
      }
      return this;
    }

    /**
     * <p>Trading session closing time on early close days</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage earlyCloseTime(String earlyCloseTime) {
      this.earlyCloseTime = Optional.ofNullable(earlyCloseTime);
      return this;
    }

    /**
     * <p>Trading session closing time on early close days</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "early_close_time",
        nulls = Nulls.SKIP
    )
    public _FinalStage earlyCloseTime(Optional<String> earlyCloseTime) {
      this.earlyCloseTime = earlyCloseTime;
      return this;
    }

    /**
     * <p>List of working days</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addAllWorkingDays(List<Weekday> workingDays) {
      if (workingDays != null) {
        this.workingDays.addAll(workingDays);
      }
      return this;
    }

    /**
     * <p>List of working days</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage addWorkingDays(Weekday workingDays) {
      this.workingDays.add(workingDays);
      return this;
    }

    /**
     * <p>List of working days</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "working_days",
        nulls = Nulls.SKIP
    )
    public _FinalStage workingDays(List<Weekday> workingDays) {
      this.workingDays.clear();
      if (workingDays != null) {
        this.workingDays.addAll(workingDays);
      }
      return this;
    }

    /**
     * <p>Date of the next DST transition</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage nextDstTransition(Nullable<String> nextDstTransition) {
      if (nextDstTransition.isNull()) {
        this.nextDstTransition = null;
      }
      else if (nextDstTransition.isEmpty()) {
        this.nextDstTransition = Optional.empty();
      }
      else {
        this.nextDstTransition = Optional.of(nextDstTransition.get());
      }
      return this;
    }

    /**
     * <p>Date of the next DST transition</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage nextDstTransition(String nextDstTransition) {
      this.nextDstTransition = Optional.ofNullable(nextDstTransition);
      return this;
    }

    /**
     * <p>Date of the next DST transition</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "next_dst_transition",
        nulls = Nulls.SKIP
    )
    public _FinalStage nextDstTransition(Optional<String> nextDstTransition) {
      this.nextDstTransition = nextDstTransition;
      return this;
    }

    /**
     * <p>Date of the previous DST transition</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage previousDstTransition(Nullable<String> previousDstTransition) {
      if (previousDstTransition.isNull()) {
        this.previousDstTransition = null;
      }
      else if (previousDstTransition.isEmpty()) {
        this.previousDstTransition = Optional.empty();
      }
      else {
        this.previousDstTransition = Optional.of(previousDstTransition.get());
      }
      return this;
    }

    /**
     * <p>Date of the previous DST transition</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage previousDstTransition(String previousDstTransition) {
      this.previousDstTransition = Optional.ofNullable(previousDstTransition);
      return this;
    }

    /**
     * <p>Date of the previous DST transition</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "previous_dst_transition",
        nulls = Nulls.SKIP
    )
    public _FinalStage previousDstTransition(Optional<String> previousDstTransition) {
      this.previousDstTransition = previousDstTransition;
      return this;
    }

    /**
     * <p>Exchange acronym</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage acronym(Nullable<String> acronym) {
      if (acronym.isNull()) {
        this.acronym = null;
      }
      else if (acronym.isEmpty()) {
        this.acronym = Optional.empty();
      }
      else {
        this.acronym = Optional.of(acronym.get());
      }
      return this;
    }

    /**
     * <p>Exchange acronym</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage acronym(String acronym) {
      this.acronym = Optional.ofNullable(acronym);
      return this;
    }

    /**
     * <p>Exchange acronym</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "acronym",
        nulls = Nulls.SKIP
    )
    public _FinalStage acronym(Optional<String> acronym) {
      this.acronym = acronym;
      return this;
    }

    @java.lang.Override
    public MarketResponse build() {
      return new MarketResponse(mic, exchange, acronym, lei, url, city, country, countryCode, flag, currencyName, currencyCode, currencySymbol, region, timezone, timezoneAbbr, utcOffset, dst, previousDstTransition, nextDstTransition, workingDays, openTime, closeTime, earlyCloseTime, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
