/**
 * This file was auto-generated by Fern from our API Definition.
 */

package io.tradewatch.client.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.tradewatch.client.core.Nullable;
import io.tradewatch.client.core.NullableNonemptyFilter;
import io.tradewatch.client.core.ObjectMappers;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = MarketStatusResponse.Builder.class
)
public final class MarketStatusResponse {
  private final String mic;

  private final String dayOfWeek;

  private final boolean isWeekend;

  private final boolean isBusinessDay;

  private final Status status;

  private final Optional<Boolean> isEarlyClose;

  private final OffsetDateTime localTime;

  private final Optional<OffsetDateTime> openTime;

  private final Optional<OffsetDateTime> closeTime;

  private final Optional<String> holidayName;

  private final Map<String, Object> additionalProperties;

  private MarketStatusResponse(String mic, String dayOfWeek, boolean isWeekend,
      boolean isBusinessDay, Status status, Optional<Boolean> isEarlyClose,
      OffsetDateTime localTime, Optional<OffsetDateTime> openTime,
      Optional<OffsetDateTime> closeTime, Optional<String> holidayName,
      Map<String, Object> additionalProperties) {
    this.mic = mic;
    this.dayOfWeek = dayOfWeek;
    this.isWeekend = isWeekend;
    this.isBusinessDay = isBusinessDay;
    this.status = status;
    this.isEarlyClose = isEarlyClose;
    this.localTime = localTime;
    this.openTime = openTime;
    this.closeTime = closeTime;
    this.holidayName = holidayName;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("mic")
  public String getMic() {
    return mic;
  }

  @JsonProperty("day_of_week")
  public String getDayOfWeek() {
    return dayOfWeek;
  }

  @JsonProperty("is_weekend")
  public boolean getIsWeekend() {
    return isWeekend;
  }

  @JsonProperty("is_business_day")
  public boolean getIsBusinessDay() {
    return isBusinessDay;
  }

  @JsonProperty("status")
  public Status getStatus() {
    return status;
  }

  @JsonIgnore
  public Optional<Boolean> getIsEarlyClose() {
    if (isEarlyClose == null) {
      return Optional.empty();
    }
    return isEarlyClose;
  }

  @JsonProperty("local_time")
  public OffsetDateTime getLocalTime() {
    return localTime;
  }

  @JsonIgnore
  public Optional<OffsetDateTime> getOpenTime() {
    if (openTime == null) {
      return Optional.empty();
    }
    return openTime;
  }

  @JsonIgnore
  public Optional<OffsetDateTime> getCloseTime() {
    if (closeTime == null) {
      return Optional.empty();
    }
    return closeTime;
  }

  @JsonIgnore
  public Optional<String> getHolidayName() {
    if (holidayName == null) {
      return Optional.empty();
    }
    return holidayName;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("is_early_close")
  private Optional<Boolean> _getIsEarlyClose() {
    return isEarlyClose;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("open_time")
  private Optional<OffsetDateTime> _getOpenTime() {
    return openTime;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("close_time")
  private Optional<OffsetDateTime> _getCloseTime() {
    return closeTime;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("holiday_name")
  private Optional<String> _getHolidayName() {
    return holidayName;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof MarketStatusResponse && equalTo((MarketStatusResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(MarketStatusResponse other) {
    return mic.equals(other.mic) && dayOfWeek.equals(other.dayOfWeek) && isWeekend == other.isWeekend && isBusinessDay == other.isBusinessDay && status.equals(other.status) && isEarlyClose.equals(other.isEarlyClose) && localTime.equals(other.localTime) && openTime.equals(other.openTime) && closeTime.equals(other.closeTime) && holidayName.equals(other.holidayName);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.mic, this.dayOfWeek, this.isWeekend, this.isBusinessDay, this.status, this.isEarlyClose, this.localTime, this.openTime, this.closeTime, this.holidayName);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static MicStage builder() {
    return new Builder();
  }

  public interface MicStage {
    DayOfWeekStage mic(@NotNull String mic);

    Builder from(MarketStatusResponse other);
  }

  public interface DayOfWeekStage {
    IsWeekendStage dayOfWeek(@NotNull String dayOfWeek);
  }

  public interface IsWeekendStage {
    IsBusinessDayStage isWeekend(boolean isWeekend);
  }

  public interface IsBusinessDayStage {
    StatusStage isBusinessDay(boolean isBusinessDay);
  }

  public interface StatusStage {
    LocalTimeStage status(@NotNull Status status);
  }

  public interface LocalTimeStage {
    _FinalStage localTime(@NotNull OffsetDateTime localTime);
  }

  public interface _FinalStage {
    MarketStatusResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage isEarlyClose(Optional<Boolean> isEarlyClose);

    _FinalStage isEarlyClose(Boolean isEarlyClose);

    _FinalStage isEarlyClose(Nullable<Boolean> isEarlyClose);

    _FinalStage openTime(Optional<OffsetDateTime> openTime);

    _FinalStage openTime(OffsetDateTime openTime);

    _FinalStage openTime(Nullable<OffsetDateTime> openTime);

    _FinalStage closeTime(Optional<OffsetDateTime> closeTime);

    _FinalStage closeTime(OffsetDateTime closeTime);

    _FinalStage closeTime(Nullable<OffsetDateTime> closeTime);

    _FinalStage holidayName(Optional<String> holidayName);

    _FinalStage holidayName(String holidayName);

    _FinalStage holidayName(Nullable<String> holidayName);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements MicStage, DayOfWeekStage, IsWeekendStage, IsBusinessDayStage, StatusStage, LocalTimeStage, _FinalStage {
    private String mic;

    private String dayOfWeek;

    private boolean isWeekend;

    private boolean isBusinessDay;

    private Status status;

    private OffsetDateTime localTime;

    private Optional<String> holidayName = Optional.empty();

    private Optional<OffsetDateTime> closeTime = Optional.empty();

    private Optional<OffsetDateTime> openTime = Optional.empty();

    private Optional<Boolean> isEarlyClose = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(MarketStatusResponse other) {
      mic(other.getMic());
      dayOfWeek(other.getDayOfWeek());
      isWeekend(other.getIsWeekend());
      isBusinessDay(other.getIsBusinessDay());
      status(other.getStatus());
      isEarlyClose(other.getIsEarlyClose());
      localTime(other.getLocalTime());
      openTime(other.getOpenTime());
      closeTime(other.getCloseTime());
      holidayName(other.getHolidayName());
      return this;
    }

    @java.lang.Override
    @JsonSetter("mic")
    public DayOfWeekStage mic(@NotNull String mic) {
      this.mic = Objects.requireNonNull(mic, "mic must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("day_of_week")
    public IsWeekendStage dayOfWeek(@NotNull String dayOfWeek) {
      this.dayOfWeek = Objects.requireNonNull(dayOfWeek, "dayOfWeek must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("is_weekend")
    public IsBusinessDayStage isWeekend(boolean isWeekend) {
      this.isWeekend = isWeekend;
      return this;
    }

    @java.lang.Override
    @JsonSetter("is_business_day")
    public StatusStage isBusinessDay(boolean isBusinessDay) {
      this.isBusinessDay = isBusinessDay;
      return this;
    }

    @java.lang.Override
    @JsonSetter("status")
    public LocalTimeStage status(@NotNull Status status) {
      this.status = Objects.requireNonNull(status, "status must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("local_time")
    public _FinalStage localTime(@NotNull OffsetDateTime localTime) {
      this.localTime = Objects.requireNonNull(localTime, "localTime must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage holidayName(Nullable<String> holidayName) {
      if (holidayName.isNull()) {
        this.holidayName = null;
      }
      else if (holidayName.isEmpty()) {
        this.holidayName = Optional.empty();
      }
      else {
        this.holidayName = Optional.of(holidayName.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage holidayName(String holidayName) {
      this.holidayName = Optional.ofNullable(holidayName);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "holiday_name",
        nulls = Nulls.SKIP
    )
    public _FinalStage holidayName(Optional<String> holidayName) {
      this.holidayName = holidayName;
      return this;
    }

    @java.lang.Override
    public _FinalStage closeTime(Nullable<OffsetDateTime> closeTime) {
      if (closeTime.isNull()) {
        this.closeTime = null;
      }
      else if (closeTime.isEmpty()) {
        this.closeTime = Optional.empty();
      }
      else {
        this.closeTime = Optional.of(closeTime.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage closeTime(OffsetDateTime closeTime) {
      this.closeTime = Optional.ofNullable(closeTime);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "close_time",
        nulls = Nulls.SKIP
    )
    public _FinalStage closeTime(Optional<OffsetDateTime> closeTime) {
      this.closeTime = closeTime;
      return this;
    }

    @java.lang.Override
    public _FinalStage openTime(Nullable<OffsetDateTime> openTime) {
      if (openTime.isNull()) {
        this.openTime = null;
      }
      else if (openTime.isEmpty()) {
        this.openTime = Optional.empty();
      }
      else {
        this.openTime = Optional.of(openTime.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage openTime(OffsetDateTime openTime) {
      this.openTime = Optional.ofNullable(openTime);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "open_time",
        nulls = Nulls.SKIP
    )
    public _FinalStage openTime(Optional<OffsetDateTime> openTime) {
      this.openTime = openTime;
      return this;
    }

    @java.lang.Override
    public _FinalStage isEarlyClose(Nullable<Boolean> isEarlyClose) {
      if (isEarlyClose.isNull()) {
        this.isEarlyClose = null;
      }
      else if (isEarlyClose.isEmpty()) {
        this.isEarlyClose = Optional.empty();
      }
      else {
        this.isEarlyClose = Optional.of(isEarlyClose.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage isEarlyClose(Boolean isEarlyClose) {
      this.isEarlyClose = Optional.ofNullable(isEarlyClose);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "is_early_close",
        nulls = Nulls.SKIP
    )
    public _FinalStage isEarlyClose(Optional<Boolean> isEarlyClose) {
      this.isEarlyClose = isEarlyClose;
      return this;
    }

    @java.lang.Override
    public MarketStatusResponse build() {
      return new MarketStatusResponse(mic, dayOfWeek, isWeekend, isBusinessDay, status, isEarlyClose, localTime, openTime, closeTime, holidayName, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
