/**
 * This file was auto-generated by Fern from our API Definition.
 */

package io.tradewatch.client.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.tradewatch.client.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = NewsMetaData.Builder.class
)
public final class NewsMetaData {
  private final Optional<List<String>> markets;

  private final Optional<List<String>> tickets;

  private final Optional<List<String>> hashtags;

  private final Map<String, Object> additionalProperties;

  private NewsMetaData(Optional<List<String>> markets, Optional<List<String>> tickets,
      Optional<List<String>> hashtags, Map<String, Object> additionalProperties) {
    this.markets = markets;
    this.tickets = tickets;
    this.hashtags = hashtags;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("markets")
  public Optional<List<String>> getMarkets() {
    return markets;
  }

  @JsonProperty("tickets")
  public Optional<List<String>> getTickets() {
    return tickets;
  }

  @JsonProperty("hashtags")
  public Optional<List<String>> getHashtags() {
    return hashtags;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof NewsMetaData && equalTo((NewsMetaData) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(NewsMetaData other) {
    return markets.equals(other.markets) && tickets.equals(other.tickets) && hashtags.equals(other.hashtags);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.markets, this.tickets, this.hashtags);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<List<String>> markets = Optional.empty();

    private Optional<List<String>> tickets = Optional.empty();

    private Optional<List<String>> hashtags = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(NewsMetaData other) {
      markets(other.getMarkets());
      tickets(other.getTickets());
      hashtags(other.getHashtags());
      return this;
    }

    @JsonSetter(
        value = "markets",
        nulls = Nulls.SKIP
    )
    public Builder markets(Optional<List<String>> markets) {
      this.markets = markets;
      return this;
    }

    public Builder markets(List<String> markets) {
      this.markets = Optional.ofNullable(markets);
      return this;
    }

    @JsonSetter(
        value = "tickets",
        nulls = Nulls.SKIP
    )
    public Builder tickets(Optional<List<String>> tickets) {
      this.tickets = tickets;
      return this;
    }

    public Builder tickets(List<String> tickets) {
      this.tickets = Optional.ofNullable(tickets);
      return this;
    }

    @JsonSetter(
        value = "hashtags",
        nulls = Nulls.SKIP
    )
    public Builder hashtags(Optional<List<String>> hashtags) {
      this.hashtags = hashtags;
      return this;
    }

    public Builder hashtags(List<String> hashtags) {
      this.hashtags = Optional.ofNullable(hashtags);
      return this;
    }

    public NewsMetaData build() {
      return new NewsMetaData(markets, tickets, hashtags, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
