/**
 * This file was auto-generated by Fern from our API Definition.
 */

package io.tradewatch.client.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.tradewatch.client.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = NewsOut.Builder.class
)
public final class NewsOut {
  private final int timestamp;

  private final String content;

  private final NewsMetaData metaData;

  private final Map<String, Object> additionalProperties;

  private NewsOut(int timestamp, String content, NewsMetaData metaData,
      Map<String, Object> additionalProperties) {
    this.timestamp = timestamp;
    this.content = content;
    this.metaData = metaData;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("timestamp")
  public int getTimestamp() {
    return timestamp;
  }

  @JsonProperty("content")
  public String getContent() {
    return content;
  }

  @JsonProperty("meta_data")
  public NewsMetaData getMetaData() {
    return metaData;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof NewsOut && equalTo((NewsOut) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(NewsOut other) {
    return timestamp == other.timestamp && content.equals(other.content) && metaData.equals(other.metaData);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.timestamp, this.content, this.metaData);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static TimestampStage builder() {
    return new Builder();
  }

  public interface TimestampStage {
    ContentStage timestamp(int timestamp);

    Builder from(NewsOut other);
  }

  public interface ContentStage {
    MetaDataStage content(@NotNull String content);
  }

  public interface MetaDataStage {
    _FinalStage metaData(@NotNull NewsMetaData metaData);
  }

  public interface _FinalStage {
    NewsOut build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements TimestampStage, ContentStage, MetaDataStage, _FinalStage {
    private int timestamp;

    private String content;

    private NewsMetaData metaData;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(NewsOut other) {
      timestamp(other.getTimestamp());
      content(other.getContent());
      metaData(other.getMetaData());
      return this;
    }

    @java.lang.Override
    @JsonSetter("timestamp")
    public ContentStage timestamp(int timestamp) {
      this.timestamp = timestamp;
      return this;
    }

    @java.lang.Override
    @JsonSetter("content")
    public MetaDataStage content(@NotNull String content) {
      this.content = Objects.requireNonNull(content, "content must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("meta_data")
    public _FinalStage metaData(@NotNull NewsMetaData metaData) {
      this.metaData = Objects.requireNonNull(metaData, "metaData must not be null");
      return this;
    }

    @java.lang.Override
    public NewsOut build() {
      return new NewsOut(timestamp, content, metaData, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
