/**
 * This file was auto-generated by Fern from our API Definition.
 */

package io.tradewatch.client.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.tradewatch.client.core.Nullable;
import io.tradewatch.client.core.NullableNonemptyFilter;
import io.tradewatch.client.core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = TradingHoursResponse.Builder.class
)
public final class TradingHoursResponse {
  private final String mic;

  private final String date;

  private final String dayOfWeek;

  private final boolean isEarlyClose;

  private final OffsetDateTime openTime;

  private final OffsetDateTime closeTime;

  private final Optional<String> holidayName;

  private final Map<String, Object> additionalProperties;

  private TradingHoursResponse(String mic, String date, String dayOfWeek, boolean isEarlyClose,
      OffsetDateTime openTime, OffsetDateTime closeTime, Optional<String> holidayName,
      Map<String, Object> additionalProperties) {
    this.mic = mic;
    this.date = date;
    this.dayOfWeek = dayOfWeek;
    this.isEarlyClose = isEarlyClose;
    this.openTime = openTime;
    this.closeTime = closeTime;
    this.holidayName = holidayName;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Market Identifier Code (ISO 10383)
   */
  @JsonProperty("mic")
  public String getMic() {
    return mic;
  }

  /**
   * @return Date of the trading session (YYYY-MM-DD)
   */
  @JsonProperty("date")
  public String getDate() {
    return date;
  }

  /**
   * @return Day of the week
   */
  @JsonProperty("day_of_week")
  public String getDayOfWeek() {
    return dayOfWeek;
  }

  /**
   * @return Whether the market closes early on this day
   */
  @JsonProperty("is_early_close")
  public boolean getIsEarlyClose() {
    return isEarlyClose;
  }

  /**
   * @return Opening time for the day
   */
  @JsonProperty("open_time")
  public OffsetDateTime getOpenTime() {
    return openTime;
  }

  /**
   * @return Closing time for the day
   */
  @JsonProperty("close_time")
  public OffsetDateTime getCloseTime() {
    return closeTime;
  }

  /**
   * @return Name of the holiday if applicable
   */
  @JsonIgnore
  public Optional<String> getHolidayName() {
    if (holidayName == null) {
      return Optional.empty();
    }
    return holidayName;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("holiday_name")
  private Optional<String> _getHolidayName() {
    return holidayName;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof TradingHoursResponse && equalTo((TradingHoursResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(TradingHoursResponse other) {
    return mic.equals(other.mic) && date.equals(other.date) && dayOfWeek.equals(other.dayOfWeek) && isEarlyClose == other.isEarlyClose && openTime.equals(other.openTime) && closeTime.equals(other.closeTime) && holidayName.equals(other.holidayName);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.mic, this.date, this.dayOfWeek, this.isEarlyClose, this.openTime, this.closeTime, this.holidayName);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static MicStage builder() {
    return new Builder();
  }

  public interface MicStage {
    /**
     * <p>Market Identifier Code (ISO 10383)</p>
     */
    DateStage mic(@NotNull String mic);

    Builder from(TradingHoursResponse other);
  }

  public interface DateStage {
    /**
     * <p>Date of the trading session (YYYY-MM-DD)</p>
     */
    DayOfWeekStage date(@NotNull String date);
  }

  public interface DayOfWeekStage {
    /**
     * <p>Day of the week</p>
     */
    IsEarlyCloseStage dayOfWeek(@NotNull String dayOfWeek);
  }

  public interface IsEarlyCloseStage {
    /**
     * <p>Whether the market closes early on this day</p>
     */
    OpenTimeStage isEarlyClose(boolean isEarlyClose);
  }

  public interface OpenTimeStage {
    /**
     * <p>Opening time for the day</p>
     */
    CloseTimeStage openTime(@NotNull OffsetDateTime openTime);
  }

  public interface CloseTimeStage {
    /**
     * <p>Closing time for the day</p>
     */
    _FinalStage closeTime(@NotNull OffsetDateTime closeTime);
  }

  public interface _FinalStage {
    TradingHoursResponse build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Name of the holiday if applicable</p>
     */
    _FinalStage holidayName(Optional<String> holidayName);

    _FinalStage holidayName(String holidayName);

    _FinalStage holidayName(Nullable<String> holidayName);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements MicStage, DateStage, DayOfWeekStage, IsEarlyCloseStage, OpenTimeStage, CloseTimeStage, _FinalStage {
    private String mic;

    private String date;

    private String dayOfWeek;

    private boolean isEarlyClose;

    private OffsetDateTime openTime;

    private OffsetDateTime closeTime;

    private Optional<String> holidayName = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(TradingHoursResponse other) {
      mic(other.getMic());
      date(other.getDate());
      dayOfWeek(other.getDayOfWeek());
      isEarlyClose(other.getIsEarlyClose());
      openTime(other.getOpenTime());
      closeTime(other.getCloseTime());
      holidayName(other.getHolidayName());
      return this;
    }

    /**
     * <p>Market Identifier Code (ISO 10383)</p>
     * <p>Market Identifier Code (ISO 10383)</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("mic")
    public DateStage mic(@NotNull String mic) {
      this.mic = Objects.requireNonNull(mic, "mic must not be null");
      return this;
    }

    /**
     * <p>Date of the trading session (YYYY-MM-DD)</p>
     * <p>Date of the trading session (YYYY-MM-DD)</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("date")
    public DayOfWeekStage date(@NotNull String date) {
      this.date = Objects.requireNonNull(date, "date must not be null");
      return this;
    }

    /**
     * <p>Day of the week</p>
     * <p>Day of the week</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("day_of_week")
    public IsEarlyCloseStage dayOfWeek(@NotNull String dayOfWeek) {
      this.dayOfWeek = Objects.requireNonNull(dayOfWeek, "dayOfWeek must not be null");
      return this;
    }

    /**
     * <p>Whether the market closes early on this day</p>
     * <p>Whether the market closes early on this day</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("is_early_close")
    public OpenTimeStage isEarlyClose(boolean isEarlyClose) {
      this.isEarlyClose = isEarlyClose;
      return this;
    }

    /**
     * <p>Opening time for the day</p>
     * <p>Opening time for the day</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("open_time")
    public CloseTimeStage openTime(@NotNull OffsetDateTime openTime) {
      this.openTime = Objects.requireNonNull(openTime, "openTime must not be null");
      return this;
    }

    /**
     * <p>Closing time for the day</p>
     * <p>Closing time for the day</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("close_time")
    public _FinalStage closeTime(@NotNull OffsetDateTime closeTime) {
      this.closeTime = Objects.requireNonNull(closeTime, "closeTime must not be null");
      return this;
    }

    /**
     * <p>Name of the holiday if applicable</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage holidayName(Nullable<String> holidayName) {
      if (holidayName.isNull()) {
        this.holidayName = null;
      }
      else if (holidayName.isEmpty()) {
        this.holidayName = Optional.empty();
      }
      else {
        this.holidayName = Optional.of(holidayName.get());
      }
      return this;
    }

    /**
     * <p>Name of the holiday if applicable</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage holidayName(String holidayName) {
      this.holidayName = Optional.ofNullable(holidayName);
      return this;
    }

    /**
     * <p>Name of the holiday if applicable</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "holiday_name",
        nulls = Nulls.SKIP
    )
    public _FinalStage holidayName(Optional<String> holidayName) {
      this.holidayName = holidayName;
      return this;
    }

    @java.lang.Override
    public TradingHoursResponse build() {
      return new TradingHoursResponse(mic, date, dayOfWeek, isEarlyClose, openTime, closeTime, holidayName, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
