/**
 * This file was auto-generated by Fern from our API Definition.
 */

package io.tradewatch.client.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class Weekday {
  public static final Weekday TUESDAY = new Weekday(Value.TUESDAY, "Tuesday");

  public static final Weekday THURSDAY = new Weekday(Value.THURSDAY, "Thursday");

  public static final Weekday FRIDAY = new Weekday(Value.FRIDAY, "Friday");

  public static final Weekday SATURDAY = new Weekday(Value.SATURDAY, "Saturday");

  public static final Weekday MONDAY = new Weekday(Value.MONDAY, "Monday");

  public static final Weekday SUNDAY = new Weekday(Value.SUNDAY, "Sunday");

  public static final Weekday WEDNESDAY = new Weekday(Value.WEDNESDAY, "Wednesday");

  private final Value value;

  private final String string;

  Weekday(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof Weekday && this.string.equals(((Weekday) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case TUESDAY:
        return visitor.visitTuesday();
      case THURSDAY:
        return visitor.visitThursday();
      case FRIDAY:
        return visitor.visitFriday();
      case SATURDAY:
        return visitor.visitSaturday();
      case MONDAY:
        return visitor.visitMonday();
      case SUNDAY:
        return visitor.visitSunday();
      case WEDNESDAY:
        return visitor.visitWednesday();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static Weekday valueOf(String value) {
    switch (value) {
      case "Tuesday":
        return TUESDAY;
      case "Thursday":
        return THURSDAY;
      case "Friday":
        return FRIDAY;
      case "Saturday":
        return SATURDAY;
      case "Monday":
        return MONDAY;
      case "Sunday":
        return SUNDAY;
      case "Wednesday":
        return WEDNESDAY;
      default:
        return new Weekday(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    MONDAY,

    TUESDAY,

    WEDNESDAY,

    THURSDAY,

    FRIDAY,

    SATURDAY,

    SUNDAY,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitMonday();

    T visitTuesday();

    T visitWednesday();

    T visitThursday();

    T visitFriday();

    T visitSaturday();

    T visitSunday();

    T visitUnknown(String unknownType);
  }
}
