/*
 * tradewatch.io
 * Financial market data for Developers
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.tradewatch.client.model;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ValidationErrorLocInner
 */
public class ValidationErrorLocInnerTest {
    private final ValidationErrorLocInner model = new ValidationErrorLocInner();

    /**
     * Model tests for ValidationErrorLocInner
     */
    @Test
    public void testValidationErrorLocInner() {
        // TODO: test ValidationErrorLocInner
    }

}
